'use strict';

const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore, FieldValue, Timestamp } = require('firebase-admin/firestore');

const serviceAccount = require('./serviceAccountKey.json');

initializeApp({
  credential: cert(serviceAccount),
});

const db = getFirestore();

// All Curated Malaysian Vendors & Places
const places = [
  // PENANG (EXPANDED CURATED REAL PLACES)
  {
    name: 'Pinang Peranakan Mansion',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art', 'Local Business'],
    interestTags: ['Heritage', 'Culture', 'Art', 'Local Business'],
    formattedAddress: '29 Church Street, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 75,
    budgetLevel: 'Medium',
    location: { latitude: 5.4182, longitude: 100.3408 },
    phone: '+604-264 2929',
    website: 'https://www.pinangperanakanmansion.com.my/',
    openingHours: 'Daily 09:30 - 17:00',
    score: 4.8,
    culturalTask: {
      title: 'Peranakan Heritage Discovery',
      description: 'Photograph one traditional Baba Nyonya antique or architectural carving and learn about Penang Peranakan customs.',
      rewardPoints: 120,
    },
    description: 'Opulent 19th-century Peranakan Baba Nyonya mansion showcasing over 1,000 ornate antiques, gold leaf woodwork, and ancestral customs.',
  },
  {
    name: 'Cheong Fatt Tze - The Blue Mansion',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art', 'Local Business'],
    interestTags: ['Heritage', 'Culture', 'Art', 'Local Business'],
    formattedAddress: '14 Leith Street, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 75,
    budgetLevel: 'High',
    location: { latitude: 5.4216, longitude: 100.3341 },
    phone: '+604-262 0006',
    website: 'https://www.cheongfatttzemansion.com/',
    openingHours: 'Daily 11:00 - 18:00',
    score: 4.7,
    culturalTask: {
      title: 'Indigo Architectural Snapshot',
      description: 'Photograph the iconic indigo courtyard and identify one unique Feng Shui element.',
      rewardPoints: 130,
    },
    description: 'Award-winning UNESCO-conserved 1890s courtyard mansion famous for its striking indigo blue walls, Art Nouveau stained glass, and Chinese master craft.',
  },
  {
    name: 'Leong San Tong Khoo Kongsi',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art'],
    interestTags: ['Heritage', 'Culture', 'Art'],
    formattedAddress: '18 Cannon Square, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4165, longitude: 100.3373 },
    phone: '+604-261 4609',
    website: 'https://www.khookongsi.com.my/',
    openingHours: 'Daily 09:00 - 17:00',
    score: 4.9,
    culturalTask: {
      title: 'Clan Architecture Study',
      description: 'Photograph the intricate granite stone carvings or ornate roof dragons at Khoo Kongsi.',
      rewardPoints: 140,
    },
    description: 'The grandest Chinese clan house in Malaysia, renowned for its opulent stone and wood carvings, dragon pillars, and clan lineage museum.',
  },
  {
    name: 'Fort Cornwallis',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture'],
    interestTags: ['Heritage', 'Culture'],
    formattedAddress: 'Jalan Tun Syed Sheh Barakbah, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4208, longitude: 100.3441 },
    phone: '+604-261 0260',
    website: 'https://www.thefortcornwallis.com/',
    openingHours: 'Daily 08:00 - 23:00',
    score: 4.5,
    culturalTask: {
      title: 'Colonial Bastion History',
      description: 'Locate the historic Seri Rambai Cannon and photograph the harbour bastion.',
      rewardPoints: 110,
    },
    description: 'Largest standing British fortress in Malaysia, constructed in 1786 by Captain Francis Light with lighthouse, chapel, and historical artillery.',
  },
  {
    name: 'Clan Jetties of Penang (Chew Jetty)',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Local Business'],
    interestTags: ['Heritage', 'Culture', 'Local Business'],
    formattedAddress: 'Weld Quay, George Town, 10300 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.4128, longitude: 100.3402 },
    phone: '+604-263 6050',
    website: '',
    openingHours: 'Daily 09:00 - 21:00',
    score: 4.7,
    culturalTask: {
      title: 'Waterfront Clan Settlement Walk',
      description: 'Photograph the stilt wooden walkway overlooking the Penang Strait and visit the waterfront temple shrine.',
      rewardPoints: 100,
    },
    description: 'Historic 19th-century wooden stilt village built over the sea by early Chinese clan immigrants, featuring timber walkways and seaside shrines.',
  },
  {
    name: 'Armenian Street Heritage Trail',
    category: 'Art',
    plannerCategories: ['Art', 'Heritage', 'Culture', 'Local Business'],
    interestTags: ['Art', 'Heritage', 'Culture', 'Local Business'],
    formattedAddress: 'Lebuh Armenian, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 75,
    budgetLevel: 'Low',
    location: { latitude: 5.415, longitude: 100.3365 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.8,
    culturalTask: {
      title: 'Street Art Photo Walk',
      description: 'Photograph the Kids on Bicycle mural and explore the surrounding heritage craft stalls.',
      rewardPoints: 100,
    },
    description: 'Iconic UNESCO heritage core known for world-famous Ernest Zacharevic street art murals, antique galleries, and souvenir shophouses.',
  },
  {
    name: 'Kapitan Keling Mosque',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture'],
    interestTags: ['Heritage', 'Culture'],
    formattedAddress: '14 Buckingham Street, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4167, longitude: 100.3372 },
    phone: '+604-261 4201',
    website: '',
    openingHours: 'Daily 09:30 - 17:30',
    score: 4.7,
    description: 'Prominent historic Indo-Moorish mosque founded in 1801 by George Town\'s early Indian Muslim community leaders.',
  },
  {
    name: 'Sri Mahamariamman Temple Queen Street',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art'],
    interestTags: ['Heritage', 'Culture', 'Art'],
    formattedAddress: 'Lebuh Queen, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.4169, longitude: 100.3397 },
    phone: '+604-262 2256',
    website: '',
    openingHours: 'Daily 06:00 - 21:00',
    score: 4.7,
    description: 'Oldest Hindu temple in Penang founded in 1833, featuring an ornate Dravidian gopuram tower adorned with sculpted deities.',
  },
  {
    name: 'St. George\'s Anglican Church',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture'],
    interestTags: ['Heritage', 'Culture'],
    formattedAddress: '1 Farquhar Street, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.4203, longitude: 100.3392 },
    phone: '+604-261 2739',
    website: '',
    openingHours: 'Tue-Sun 09:00 - 17:00',
    score: 4.6,
    description: 'Oldest purpose-built Anglican church in Southeast Asia, constructed in 1818 with Georgian neoclassical Doric columns and a memorial canopy.',
  },
  {
    name: 'Han Jiang Ancestral Temple (Teochew Association)',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art'],
    interestTags: ['Heritage', 'Culture', 'Art'],
    formattedAddress: '127 Lebuh Chulia, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.417, longitude: 100.3382 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 08:30 - 17:00',
    score: 4.7,
    description: 'UNESCO Award-winning Teochew ancestral temple founded in 1870, famous for its intricate Teochew wood carvings and gilded altars.',
  },
  {
    name: 'Sun Yat Sen Museum Penang',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Local Business'],
    interestTags: ['Heritage', 'Culture', 'Local Business'],
    formattedAddress: '120 Armenian Street, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.4153, longitude: 100.3361 },
    phone: '+604-262 0123',
    website: '',
    openingHours: 'Daily 09:00 - 17:00',
    score: 4.6,
    description: 'Historic shophouse base where Dr. Sun Yat-sen planned the 1911 Guangzhou uprising, preserving period courtyard furniture and historical archives.',
  },
  {
    name: 'Suffolk House',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Food', 'Local Business'],
    interestTags: ['Heritage', 'Culture', 'Food', 'Local Business'],
    formattedAddress: '250 Jalan Air Itam, George Town, 10460 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'High',
    location: { latitude: 5.4103, longitude: 100.3069 },
    phone: '+604-228 3930',
    website: '',
    openingHours: 'Daily 11:00 - 22:00',
    score: 4.7,
    description: 'Malaysia\'s only surviving Anglo-Indian Georgian mansion, former residence of early governors, now hosting heritage tours and fine English high tea.',
  },
  {
    name: 'Penang Town Hall & City Hall Esplanade',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art'],
    interestTags: ['Heritage', 'Culture', 'Art'],
    formattedAddress: 'Jalan Padang Kota Lama, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4217, longitude: 100.3414 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.7,
    description: 'Majestic Victorian & Edwardian colonial municipal buildings overlooking Padang Kota Lama and the northern seafront promenade.',
  },
  {
    name: 'Penang State Museum and Art Gallery',
    category: 'Art',
    plannerCategories: ['Art', 'Heritage', 'Culture'],
    interestTags: ['Art', 'Heritage', 'Culture'],
    formattedAddress: 'Lebuh Farquhar, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.4208, longitude: 100.3396 },
    phone: '+604-226 1462',
    website: '',
    openingHours: 'Sat-Thu 09:00 - 17:00',
    score: 4.6,
    description: 'State cultural gallery preserving Penang\'s historical paintings, antique oil canvasses, colonial artifacts, and rotating contemporary Malaysian art.',
  },
  {
    name: 'Seh Tek Tong Cheah Kongsi',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art'],
    interestTags: ['Heritage', 'Culture', 'Art'],
    formattedAddress: '8 Lebuh Pantai, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4157, longitude: 100.3385 },
    phone: '+604-261 0107',
    website: '',
    openingHours: 'Daily 09:00 - 17:00',
    score: 4.7,
    description: 'One of Penang\'s oldest Hokkien clan organizations, noted for its fortified compound, ornate sweep roofs, and lion statues.',
  },
  {
    name: 'Yap Kongsi & Choo Chay Keong Temple',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art'],
    interestTags: ['Heritage', 'Culture', 'Art'],
    formattedAddress: '71 Lebuh Armenian, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 35,
    budgetLevel: 'Low',
    location: { latitude: 5.4158, longitude: 100.3369 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 09:00 - 17:00',
    score: 4.6,
    description: 'Historic clan temple at the corner of Armenian Street boasting Straits Chinese embellishments and dragon stone carvings.',
  },
  {
    name: 'Tan Jetty Waterfront Heritage',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Local Business'],
    interestTags: ['Heritage', 'Culture', 'Local Business'],
    formattedAddress: 'Weld Quay, George Town, 10300 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.4121, longitude: 100.3395 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 09:00 - 21:00',
    score: 4.6,
    description: 'Historic wooden clan jetty with a picturesque extended timber pier extending far out into the Penang harbor.',
  },
  {
    name: 'Queen Victoria Memorial Clock Tower',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture'],
    interestTags: ['Heritage', 'Culture'],
    formattedAddress: 'Lebuh Light, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 30,
    budgetLevel: 'Low',
    location: { latitude: 5.4194, longitude: 100.344 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.6,
    description: '60-foot Moorish clock tower commissioned in 1897 by local millionaire Cheah Chen Eok to celebrate Queen Victoria\'s Diamond Jubilee.',
  },
  {
    name: 'House of Yeap Chor Ee',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Local Business'],
    interestTags: ['Heritage', 'Culture', 'Local Business'],
    formattedAddress: '4 Lebuh Penang, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4187, longitude: 100.3421 },
    phone: '+604-261 0288',
    website: '',
    openingHours: 'Mon-Fri 09:30 - 17:00',
    score: 4.6,
    description: 'Heritage museum documenting the life and rags-to-riches legacy of Penang tycoon and Ban Hin Lee Bank founder Yeap Chor Ee.',
  },
  {
    name: 'Hin Bus Depot Arts Centre',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Local Business'],
    interestTags: ['Art', 'Culture', 'Local Business'],
    formattedAddress: '31A Jalan Gurdwara, George Town, 10300 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4124, longitude: 100.3297 },
    phone: '+604-218 9004',
    website: 'https://hinbusdepot.com/',
    openingHours: 'Mon-Fri 12:00 - 19:00, Sat-Sun 11:00 - 19:00',
    score: 4.7,
    culturalTask: {
      title: 'Artisan Depot Mural Explorer',
      description: 'Explore the open art courtyard and photograph Ernest Zacharevic murals or weekend artisan crafts.',
      rewardPoints: 110,
    },
    description: 'A thriving community art space set within a restored 1940s Art Deco bus depot, hosting open-air murals, art exhibitions, artisan cafes, and craft markets.',
  },
  {
    name: 'ChinaHouse Penang',
    category: 'Food',
    plannerCategories: ['Food', 'Art', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Art', 'Culture', 'Local Business'],
    formattedAddress: '153 Beach Street & 183B Victoria Street, George Town, 10300 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4147, longitude: 100.3392 },
    phone: '+604-263 7299',
    website: 'https://www.chinahouse.com.my/',
    openingHours: 'Daily 09:00 - 00:00',
    score: 4.7,
    culturalTask: {
      title: 'Longest Shophouse Art & Cake Walk',
      description: 'Walk through the 400-ft connected heritage shophouse compound and photograph the iconic cake table display.',
      rewardPoints: 100,
    },
    description: 'Traditional heritage compound made of three linked heritage shophouses with an open courtyard, art galleries, live music, and over 30 varieties of daily cakes.',
  },
  {
    name: 'Jawi House Cafe Gallery',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Art', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Art', 'Local Business'],
    formattedAddress: '85 Armenian Street, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4152, longitude: 100.3364 },
    phone: '+604-261 3680',
    website: 'https://jawihouse.com/',
    openingHours: 'Wed-Mon 11:00 - 21:30',
    score: 4.7,
    culturalTask: {
      title: 'Jawi Peranakan Spice Heritage',
      description: 'Taste authentic Jawi Peranakan Nasi Lemuni or Herbal Rice and snap a photo of the heritage dining interior.',
      rewardPoints: 110,
    },
    description: 'Michelin-selected culinary gallery celebrating Jawi Peranakan gastronomy, featuring Nasi Lemuni, herbal curries, and antique art gallery displays.',
  },
  {
    name: 'Wonderfood Museum Penang',
    category: 'Culture',
    plannerCategories: ['Culture', 'Food', 'Art', 'Local Business'],
    interestTags: ['Culture', 'Food', 'Art', 'Local Business'],
    formattedAddress: '49 Beach Street, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4163, longitude: 100.3411 },
    phone: '+604-262 9504',
    website: '',
    openingHours: 'Daily 09:00 - 18:00',
    score: 4.6,
    culturalTask: {
      title: 'Giant Hawker Food Snap',
      description: 'Pose alongside giant replica dishes of Laksa, Cendol, or Roti Canai to document Malaysian street food heritage.',
      rewardPoints: 100,
    },
    description: 'Vibrant interactive museum displaying hyper-realistic giant replicas of Malaysian street foods, traditional cooking crafts, and colonial banquet dioramas.',
  },
  {
    name: 'Tek Sen Restaurant',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: '18 Carnarvon Street, George Town, 10100 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4172, longitude: 100.3355 },
    phone: '+6012-981 5117',
    website: '',
    openingHours: 'Wed-Mon 12:00 - 14:30, 18:00 - 20:30',
    score: 4.8,
    description: 'Michelin Bib Gourmand heritage Cantonese and Teochew zi char eatery established in 1965, famous for double-cooked pork belly and Assam fish.',
  },
  {
    name: 'Hameediyah Restaurant (Est. 1907)',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Heritage', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Heritage', 'Local Business'],
    formattedAddress: '164A Campbell Street, George Town, 10100 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 50,
    budgetLevel: 'Medium',
    location: { latitude: 5.4172, longitude: 100.333 },
    phone: '+604-261 1095',
    website: 'https://hameediyah.my/',
    openingHours: 'Daily 10:00 - 22:00',
    score: 4.8,
    description: 'The oldest surviving Nasi Kandar establishment in Malaysia, serving signature spice curries, duck rendang, and crispy murtabak on Campbell Street since 1907.',
  },
  {
    name: 'Penang Road Famous Teochew Chendul',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: '27 & 29 Lebuh Keng Kwee, George Town, 10100 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 30,
    budgetLevel: 'Low',
    location: { latitude: 5.4183, longitude: 100.331 },
    phone: '+604-262 6002',
    website: 'https://www.chendul.my/',
    openingHours: 'Daily 10:30 - 19:00',
    score: 4.7,
    description: 'Legendary roadside dessert stall founded in 1936 serving signature Teochew chendul with fresh coconut milk, pandan jelly noodles, and fragrant Gula Melaka.',
  },
  {
    name: 'Line Clear Nasi Kandar',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: '177 Jalan Penang, George Town, 10000 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Medium',
    location: { latitude: 5.4198, longitude: 100.3323 },
    phone: '+604-261 4440',
    website: '',
    openingHours: 'Daily 07:00 - 23:00',
    score: 4.6,
    description: 'Legendary Penang alleyway eatery serving rich, aromatic mixed curry gravies and spiced fried chicken since 1930.',
  },
  {
    name: 'Ghee Hiang Heritage Pastry & Sesame Oil (Since 1856)',
    category: 'Food',
    plannerCategories: ['Food', 'Heritage', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Heritage', 'Culture', 'Local Business'],
    formattedAddress: '216 Jalan Macalister, George Town, 10400 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 40,
    budgetLevel: 'Medium',
    location: { latitude: 5.4162, longitude: 100.3204 },
    phone: '+604-227 2222',
    website: 'https://ghee-hiang.com/',
    openingHours: 'Daily 09:00 - 18:00',
    score: 4.8,
    description: 'Penang\'s oldest traditional bakery brand founded in 1856, renowned for handcrafted Tau Sar Piah pastries and aromatic pure sesame seed oil.',
  },
  {
    name: 'Ban Heang Pastry Heritage Bakery',
    category: 'Food',
    plannerCategories: ['Food', 'Heritage', 'Local Business'],
    interestTags: ['Food', 'Heritage', 'Local Business'],
    formattedAddress: '200 Jalan Macalister, George Town, 10400 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 35,
    budgetLevel: 'Medium',
    location: { latitude: 5.416, longitude: 100.321 },
    phone: '+604-229 5018',
    website: '',
    openingHours: 'Daily 09:00 - 19:00',
    score: 4.7,
    description: 'Famous Penang pastry house known for crispy Tambun biscuits, heong peah, and traditional handmade confectionery.',
  },
  {
    name: 'Him Heang Traditional Tambun Biscuits',
    category: 'Food',
    plannerCategories: ['Food', 'Heritage', 'Local Business'],
    interestTags: ['Food', 'Heritage', 'Local Business'],
    formattedAddress: '163 Jalan Burma, George Town, 10050 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 35,
    budgetLevel: 'Medium',
    location: { latitude: 5.4225, longitude: 100.322 },
    phone: '+604-228 6129',
    website: '',
    openingHours: 'Mon-Sat 09:30 - 15:00',
    score: 4.7,
    description: 'Multi-generational heritage biscuit specialist famous for fresh oven-baked Tambun biscuits, Beh Teh Saw, and savoury pastry rolls.',
  },
  {
    name: 'Moh Teng Pheow Nyonya Koay',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Heritage', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Heritage', 'Local Business'],
    formattedAddress: 'Lebuh Chulia, Jalan Masjid, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.419, longitude: 100.3362 },
    phone: '+6012-415 2677',
    website: '',
    openingHours: 'Tue-Sun 10:30 - 17:00',
    score: 4.7,
    description: 'Historic Nyonya kuih canteen and workshop manufacturing colourful handmade kuih talam, ang ku kueh, and nasi ulam since 1933.',
  },
  {
    name: 'Toh Soon Cafe (Charcoal Toast & Coffee)',
    category: 'Food',
    plannerCategories: ['Food', 'Heritage', 'Local Business'],
    interestTags: ['Food', 'Heritage', 'Local Business'],
    formattedAddress: 'Campbell Street Off Lebuh Campbell, George Town, 10100 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.4188, longitude: 100.3323 },
    phone: '+604-261 3832',
    website: '',
    openingHours: 'Mon-Sat 08:00 - 17:00',
    score: 4.6,
    description: 'Iconic alleyway breakfast institution toasting bread over glowing charcoal drums, served with homemade kaya and half-boiled eggs.',
  },
  {
    name: 'Siam Road Charcoal Char Koay Teow',
    category: 'Food',
    plannerCategories: ['Food', 'Local Business'],
    interestTags: ['Food', 'Local Business'],
    formattedAddress: '82 Jalan Siam, George Town, 10400 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4147, longitude: 100.3205 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Tue-Sat 12:00 - 18:00',
    score: 4.8,
    description: 'World-famous Michelin Bib Gourmand char koay teow fried with rich pork lard, succulent prawns, cockles, and smoky charcoal wok hei.',
  },
  {
    name: 'Gurney Drive Hawker Centre',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: '172 Solok Gurney 1, George Town, 10250 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4398, longitude: 100.309 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 17:00 - 23:30',
    score: 4.6,
    description: 'Penang\'s premier seafront open-air hawker promenade gathering over 50 classic Penang street foods including oyster omelettes, rojak, and pasembur.',
  },
  {
    name: 'Kimberley Street Food Night Market',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: 'Lebuh Kimberley, George Town, 10100 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.4164, longitude: 100.3328 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 17:00 - 23:00',
    score: 4.7,
    description: 'Historic food street celebrated for the Four Heavenly Kings hawkers: Duck Kway Chap, Char Koay Teow, Si Koh Sui dessert, and Braised Chicken Feet.',
  },
  {
    name: 'New Lane Hawker Stalls (Lorong Baru)',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: 'Lorong Baru, George Town, 10450 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 55,
    budgetLevel: 'Low',
    location: { latitude: 5.4144, longitude: 100.3262 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Thu-Tue 16:00 - 23:00',
    score: 4.6,
    description: 'Bustling roadside evening food street crowded with pop-up hawker carts serving grilled chicken wings, chee cheong fun, and popiah.',
  },
  {
    name: 'Deen Maju Nasi Kandar',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: '170 Jalan Gurdwara, George Town, 10300 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Medium',
    location: { latitude: 5.4108, longitude: 100.3286 },
    phone: '+6012-425 2137',
    website: '',
    openingHours: 'Daily 12:00 - 23:00',
    score: 4.7,
    description: 'Beloved local Nasi Kandar hotspot acclaimed for crispy spiced fried chicken, signature thick Kuah Campur, and coconut sambal.',
  },
  {
    name: 'Little India Penang Cultural District',
    category: 'Culture',
    plannerCategories: ['Culture', 'Heritage', 'Food', 'Local Business'],
    interestTags: ['Culture', 'Heritage', 'Food', 'Local Business'],
    formattedAddress: 'Lebuh Pasar, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4165, longitude: 100.34 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 09:00 - 22:00',
    score: 4.7,
    description: 'Vibrant ethnic quarter filled with Bollywood melodies, colourful saree shops, aromatic spice merchants, and traditional Indian sweet stalls.',
  },
  {
    name: 'Chowrasta Market Heritage Traders',
    category: 'Culture',
    plannerCategories: ['Culture', 'Local Business', 'Food'],
    interestTags: ['Culture', 'Local Business', 'Food'],
    formattedAddress: 'Jalan Penang, George Town, 10100 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.4173, longitude: 100.3312 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 06:30 - 18:00',
    score: 4.6,
    description: 'Historic marketplace dating back to the 1890s, famous for preserved nutmeg pickles, traditional fresh produce, and second-hand book lofts.',
  },
  {
    name: 'Art Lane George Town',
    category: 'Art',
    plannerCategories: ['Art', 'Heritage', 'Culture'],
    interestTags: ['Art', 'Heritage', 'Culture'],
    formattedAddress: '127 Victoria Street, George Town, 10300 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.414, longitude: 100.3398 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 09:00 - 19:00',
    score: 4.6,
    description: 'Open public gallery stretching through transformed heritage shophouses adorned with vibrant modern graffiti, paintings, and community art.',
  },
  {
    name: 'Muntri Street Art & Shophouses',
    category: 'Art',
    plannerCategories: ['Art', 'Heritage', 'Culture', 'Local Business'],
    interestTags: ['Art', 'Heritage', 'Culture', 'Local Business'],
    formattedAddress: 'Lebuh Muntri, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.4202, longitude: 100.3348 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.7,
    description: 'Elegant heritage lane preserving 19th-century Straits eclectic shophouses, Ernest Zacharevic murals, and artisan lifestyle cafes.',
  },
  {
    name: 'Penang 3D Trick Art Museum',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Local Business'],
    interestTags: ['Art', 'Culture', 'Local Business'],
    formattedAddress: '10 Lebuh Penang, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.419, longitude: 100.3415 },
    phone: '+604-263 1628',
    website: '',
    openingHours: 'Daily 09:00 - 18:00',
    score: 4.6,
    description: 'Interactive optical illusion museum with 3D paintings depicting Penang clan jetties, Trishaw rides, and fantasy themes.',
  },
  {
    name: 'Upside Down Museum Penang',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Local Business'],
    interestTags: ['Art', 'Culture', 'Local Business'],
    formattedAddress: '45 Lebuh Kimberley, George Town, 10100 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 50,
    budgetLevel: 'Medium',
    location: { latitude: 5.4162, longitude: 100.3325 },
    phone: '+604-264 2626',
    website: '',
    openingHours: 'Daily 09:00 - 18:30',
    score: 4.6,
    description: 'Fun, inverted interactive exhibition rooms with upside-down heritage living rooms, Penang kopitiams, and street scenes.',
  },
  {
    name: 'Penang House of Music',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Heritage'],
    interestTags: ['Art', 'Culture', 'Heritage'],
    formattedAddress: 'Level 4, KOMTAR, Jalan Penang, 10000 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.414, longitude: 100.3302 },
    phone: '+604-370 6675',
    website: '',
    openingHours: 'Daily 11:00 - 20:00',
    score: 4.8,
    description: 'Interactive musical heritage gallery celebrating Penang\'s vibrant 20th-century music, Bangsawan theater, and radio history.',
  },
  {
    name: 'Batik Painting Museum Penang',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Heritage', 'Local Business'],
    interestTags: ['Art', 'Culture', 'Heritage', 'Local Business'],
    formattedAddress: '19 Armenian Street, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.4154, longitude: 100.3364 },
    phone: '+604-262 0150',
    website: '',
    openingHours: 'Daily 10:00 - 18:00',
    score: 4.7,
    description: 'Dedicated fine art museum tracing the history of Malaysian batik painting from the 1950s pioneer Chuah Thean Teng to contemporary masters.',
  },
  {
    name: 'Penang Glass Museum',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Local Business'],
    interestTags: ['Art', 'Culture', 'Local Business'],
    formattedAddress: '6 Jalan Burma, George Town, 10050 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Medium',
    location: { latitude: 5.4188, longitude: 100.33 },
    phone: '+604-251 9880',
    website: '',
    openingHours: 'Mon-Fri 09:30 - 18:00, Sat 09:30 - 17:00',
    score: 4.6,
    description: 'Specialty glass craft gallery showcasing stained glass artwork, 3D glass carving, mirror murals, and glass crafting workshops.',
  },
  {
    name: 'Ghost Museum Penang (Cultural Folklore)',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Local Business'],
    interestTags: ['Art', 'Culture', 'Local Business'],
    formattedAddress: '57 Lebuh Melayu, George Town, 10100 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 50,
    budgetLevel: 'Medium',
    location: { latitude: 5.4148, longitude: 100.3349 },
    phone: '+604-261 2352',
    website: '',
    openingHours: 'Daily 10:00 - 19:00',
    score: 4.6,
    description: 'Cultural museum showcasing Malaysian, Chinese, and global folklore myths with detailed theatrical sets and costume photo areas.',
  },
  {
    name: 'Colonial Penang Museum',
    category: 'Art',
    plannerCategories: ['Art', 'Heritage', 'Culture'],
    interestTags: ['Art', 'Heritage', 'Culture'],
    formattedAddress: '4 Jalan Sultan Ahmad Shah, George Town, 10050 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4285, longitude: 100.312 },
    phone: '+604-228 8888',
    website: '',
    openingHours: 'Daily 09:30 - 18:30',
    score: 4.6,
    description: 'Museum housing authentic colonial antiques, marble statues, master oil paintings, and original reverse glass paintings of the 19th century.',
  },
  {
    name: 'Ernest Zacharevic \'Boy on a Motorbike\' Mural',
    category: 'Art',
    plannerCategories: ['Art', 'Heritage', 'Culture'],
    interestTags: ['Art', 'Heritage', 'Culture'],
    formattedAddress: '12 Lebuh Ah Quee, George Town, 10200 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 25,
    budgetLevel: 'Low',
    location: { latitude: 5.4158, longitude: 100.337 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.8,
    description: 'World-famous heritage street art mural integrating an actual vintage motorcycle with wall painting on historic Lebuh Ah Quee.',
  },
  {
    name: 'Ernest Zacharevic \'Brother & Sister on a Swing\' Mural',
    category: 'Art',
    plannerCategories: ['Art', 'Heritage', 'Culture'],
    interestTags: ['Art', 'Heritage', 'Culture'],
    formattedAddress: 'Gat Lebuh Chulia, George Town, 10300 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 25,
    budgetLevel: 'Low',
    location: { latitude: 5.4146, longitude: 100.34 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.7,
    description: 'Charming interactive mural on Gat Lebuh Chulia depicting two smiling siblings swinging on an installed timber swing.',
  },
  {
    name: 'Penang Botanic Gardens (Waterfall Gardens)',
    category: 'Nature',
    plannerCategories: ['Nature', 'Heritage'],
    interestTags: ['Nature', 'Heritage'],
    formattedAddress: '673A Jalan Kebun Bunga, George Town, 10350 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 75,
    budgetLevel: 'Low',
    location: { latitude: 5.4378, longitude: 100.2905 },
    phone: '+604-226 4401',
    website: '',
    openingHours: 'Daily 06:30 - 19:00',
    score: 4.7,
    description: 'Historic 1884 botanical gardens surrounded by verdant hills, ancient rainforest trees, lily ponds, and macaque monkeys.',
  },
  {
    name: 'Youth Park Penang (Taman Belia)',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Persiaran Kuari, George Town, 10450 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.431, longitude: 100.298 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 06:00 - 19:30',
    score: 4.7,
    description: 'Expansive green recreation park with natural stream pools, shaded forest walking trails, outdoor gymnasiums, and lush canopy trees.',
  },
  {
    name: 'Kek Lok Si Temple',
    category: 'Culture',
    plannerCategories: ['Culture', 'Heritage', 'Nature'],
    interestTags: ['Culture', 'Heritage', 'Nature'],
    formattedAddress: 'Tingkat Lembah Ria 1, 11500 Ayer Itam, Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 90,
    budgetLevel: 'Low',
    location: { latitude: 5.3995, longitude: 100.2737 },
    phone: '+604-828 3317',
    website: 'https://kekloksitemple.com/',
    openingHours: 'Daily 08:30 - 17:30',
    score: 4.9,
    culturalTask: {
      title: 'Pagoda of Ten Thousand Buddhas',
      description: 'Climb the 7-tier Pagoda combining Chinese, Thai, and Burmese architectural tiers and photograph the view.',
      rewardPoints: 140,
    },
    description: 'The largest Buddhist temple in Malaysia, featuring the 7-tier Pagoda of Ten Thousand Buddhas, tranquil turtle liberation pond, and towering bronze Guanyin statue.',
  },
  {
    name: 'Penang Hill Biosphere Nature Reserve',
    category: 'Nature',
    plannerCategories: ['Nature', 'Heritage'],
    interestTags: ['Nature', 'Heritage'],
    formattedAddress: 'Bukit Bendera, 11500 Ayer Itam, Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 120,
    budgetLevel: 'Medium',
    location: { latitude: 5.4244, longitude: 100.2687 },
    phone: '+604-828 8880',
    website: 'https://www.penanghill.gov.my/',
    openingHours: 'Daily 06:30 - 22:00',
    score: 4.8,
    description: 'Lush UNESCO Biosphere rainforest peak accessed via century-old funicular railway, offering panoramic island vistas and cool mountain air.',
  },
  {
    name: 'The Habitat Penang Hill',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business'],
    interestTags: ['Nature', 'Local Business'],
    formattedAddress: 'Bukit Bendera, 11300 Ayer Itam, Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 120,
    budgetLevel: 'High',
    location: { latitude: 5.4243, longitude: 100.2687 },
    phone: '+604-826 7677',
    website: 'https://thehabitat.my/',
    openingHours: 'Daily 09:00 - 19:00',
    score: 4.8,
    culturalTask: {
      title: 'Curtis Crest Rainforest Canopy Walk',
      description: 'Walk along the tree canopy bridge and Curtis Crest 360 platform in the 130-million-year-old rainforest.',
      rewardPoints: 150,
    },
    description: 'World-class eco-tourism rainforest reserve inside the UNESCO Biosphere Reserve on Penang Hill, featuring Curtis Crest 360 treetop canopy walk and pristine jungle trails.',
  },
  {
    name: 'The Owl Museum Penang Hill',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Nature', 'Local Business'],
    interestTags: ['Art', 'Culture', 'Nature', 'Local Business'],
    formattedAddress: 'Astaka Bukit Bendera, 11300 Ayer Itam, Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4241, longitude: 100.269 },
    phone: '+604-826 5704',
    website: '',
    openingHours: 'Daily 09:00 - 18:00',
    score: 4.6,
    description: 'Southeast Asia\'s first owl-themed art museum showcasing over 1,000 fascinating owl sculptures, paintings, and handicrafts from across the globe.',
  },
  {
    name: 'Pasar Air Itam Laksa',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: '1 Jalan Pasar, 11500 Ayer Itam, Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4013, longitude: 100.2781 },
    phone: '+6012-500 7063',
    website: '',
    openingHours: 'Daily 10:30 - 19:00',
    score: 4.7,
    description: 'Iconic market stall operating since 1955 at the foot of Kek Lok Si, known for rich tamarind mackerel broth, fresh mint, and dark prawn paste.',
  },
  {
    name: 'Sister Curry Mee Air Itam',
    category: 'Food',
    plannerCategories: ['Food', 'Heritage', 'Local Business'],
    interestTags: ['Food', 'Heritage', 'Local Business'],
    formattedAddress: '612 T, Jalan Air Itam, 11500 Ayer Itam, Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.401, longitude: 100.2785 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Wed-Mon 07:30 - 13:00',
    score: 4.7,
    description: 'Legendary roadside stall run by two elderly sisters since 1946, serving charcoal-simmered coconut curry noodles with cuttlefish and chili sambal.',
  },
  {
    name: 'Air Itam Dam & Mountain Trail',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Jalan Balik Pulau, 11500 Ayer Itam, Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.397, longitude: 100.264 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 07:00 - 19:00',
    score: 4.7,
    description: 'Scenic hilltop reservoir lake surrounded by forest ridges, popular with morning runners and nature walkers.',
  },
  {
    name: 'Penang National Park (Taman Negara Pulau Pinang)',
    category: 'Nature',
    plannerCategories: ['Nature', 'Heritage'],
    interestTags: ['Nature', 'Heritage'],
    formattedAddress: 'Jalan Hassan Abbas, Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 120,
    budgetLevel: 'Low',
    location: { latitude: 5.46, longitude: 100.2078 },
    phone: '+604-881 3530',
    website: '',
    openingHours: 'Daily 08:00 - 17:00',
    score: 4.7,
    description: 'Malaysia\'s smallest national park featuring coastal jungle hikes, meromictic lake, secluded sandy bays, and lighthouse trails.',
  },
  {
    name: 'Monkey Beach (Teluk Duyung)',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Penang National Park, Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 90,
    budgetLevel: 'Medium',
    location: { latitude: 5.477, longitude: 100.198 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 08:00 - 17:00',
    score: 4.6,
    description: 'Pristine sandy cove tucked inside the national park, reachable by scenic coastal trail or boat ride from Teluk Bahang jetty.',
  },
  {
    name: 'Pantai Kerachut & Turtle Sanctuary',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Penang National Park, Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 90,
    budgetLevel: 'Low',
    location: { latitude: 5.459, longitude: 100.176 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 08:00 - 17:00',
    score: 4.7,
    description: 'Serene beach known for its seasonal green sea turtle nesting center, suspension bridge, and unique dual-layer meromictic lake.',
  },
  {
    name: 'Tropical Spice Garden',
    category: 'Nature',
    plannerCategories: ['Nature', 'Culture', 'Heritage', 'Local Business'],
    interestTags: ['Nature', 'Culture', 'Heritage', 'Local Business'],
    formattedAddress: 'Lot 595 Mukim 2, Jalan Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 75,
    budgetLevel: 'Medium',
    location: { latitude: 5.4628, longitude: 100.2289 },
    phone: '+604-881 1797',
    website: 'https://tropicalspicegarden.com/',
    openingHours: 'Daily 09:00 - 16:30',
    score: 4.8,
    description: 'Award-winning eco-sanctuary showcasing over 500 species of living tropical herbs, culinary spices, jungle trails, and cooking school.',
  },
  {
    name: 'Entopia by Penang Butterfly Farm',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business'],
    interestTags: ['Nature', 'Local Business'],
    formattedAddress: '830 Jalan Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 90,
    budgetLevel: 'Medium',
    location: { latitude: 5.4468, longitude: 100.2155 },
    phone: '+604-888 8111',
    website: 'https://www.entopia.com/',
    openingHours: 'Thu-Tue 09:00 - 17:00',
    score: 4.7,
    description: 'Giant glasshouse eco-sanctuary with thousands of free-flying butterflies, live reptiles, and interactive indoor nature discovery centers.',
  },
  {
    name: 'ESCAPE Penang Adventure Park',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business'],
    interestTags: ['Nature', 'Local Business'],
    formattedAddress: '828 Jalan Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 180,
    budgetLevel: 'High',
    location: { latitude: 5.4485, longitude: 100.2152 },
    phone: '+604-881 1106',
    website: 'https://www.escape.my/',
    openingHours: 'Tue-Sun 10:00 - 18:00',
    score: 4.8,
    description: 'Guinness World Record-holding forest adventure theme park featuring the world\'s longest water slide, ziplining, and obstacle ropes in lush nature.',
  },
  {
    name: 'Teluk Bahang Forest Eco Park (Taman Rimba)',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Jalan Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.4475, longitude: 100.2168 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 07:00 - 18:00',
    score: 4.6,
    description: 'Tranquil state forest park featuring natural river cascades, shady forest walking trails, picnic gazebos, and a forestry museum.',
  },
  {
    name: 'Teluk Bahang Dam Scenic Lookout',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Jalan Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.442, longitude: 100.217 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 07:00 - 19:00',
    score: 4.6,
    description: 'Spectacular reservoir dam providing wide scenic vistas across turquoise waters framed by coastal mountain ridges.',
  },
  {
    name: 'Penang Batik Factory',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Local Business', 'Heritage'],
    interestTags: ['Art', 'Culture', 'Local Business', 'Heritage'],
    formattedAddress: '665 Teluk Bahang, 11050 Penang, Malaysia',
    area: 'Teluk Bahang',
    durationMinutes: 50,
    budgetLevel: 'Medium',
    location: { latitude: 5.4578, longitude: 100.2185 },
    phone: '+604-885 1284',
    website: '',
    openingHours: 'Daily 09:00 - 17:30',
    score: 4.6,
    description: 'One of the pioneers of batik printing in Penang established in 1973, offering live canting wax demonstrations and authentic hand-painted silk batiks.',
  },
  {
    name: 'Batu Ferringhi Beach & Coastal Trail',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business'],
    interestTags: ['Nature', 'Local Business'],
    formattedAddress: 'Jalan Batu Ferringhi, 11100 Batu Ferringhi, Penang, Malaysia',
    area: 'Batu Ferringhi',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.4744, longitude: 100.2472 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.7,
    description: 'Famous white sand coastline along northern Penang with coastal sea breezes, water sports, beach cafes, and sunset viewpoints.',
  },
  {
    name: 'Moonlight Bay Coastal Point',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Jalan Batu Ferringhi, 11100 Batu Ferringhi, Penang, Malaysia',
    area: 'Batu Ferringhi',
    durationMinutes: 35,
    budgetLevel: 'Low',
    location: { latitude: 5.472, longitude: 100.261 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.6,
    description: 'Scenic cliffside rocky coast between Batu Ferringhi and Tanjung Bungah with crashing waves and sunset views.',
  },
  {
    name: 'Miami Beach Penang (Batu Ferringhi)',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business'],
    interestTags: ['Nature', 'Local Business'],
    formattedAddress: 'Jalan Batu Ferringhi, 11100 Batu Ferringhi, Penang, Malaysia',
    area: 'Batu Ferringhi',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.475, longitude: 100.268 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.6,
    description: 'Shaded sandy beach cove popular for quiet ocean strolls, coconut drink stalls, and coastal rock formations.',
  },
  {
    name: 'Yahong Art Gallery & Batik Studio',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Local Business'],
    interestTags: ['Art', 'Culture', 'Local Business'],
    formattedAddress: '58D Batu Ferringhi, 11100 Penang, Malaysia',
    area: 'Batu Ferringhi',
    durationMinutes: 50,
    budgetLevel: 'Medium',
    location: { latitude: 5.4735, longitude: 100.2458 },
    phone: '+604-881 1251',
    website: '',
    openingHours: 'Daily 09:00 - 18:00',
    score: 4.7,
    description: 'Art gallery founded by renowned batik painting master Chuah Thean Teng, exhibiting original fine art batiks, Chinese ink paintings, and antiques.',
  },
  {
    name: 'Long Beach Food Court & Seafood',
    category: 'Food',
    plannerCategories: ['Food', 'Local Business'],
    interestTags: ['Food', 'Local Business'],
    formattedAddress: 'Jalan Batu Ferringhi, 11100 Batu Ferringhi, Penang, Malaysia',
    area: 'Batu Ferringhi',
    durationMinutes: 50,
    budgetLevel: 'Medium',
    location: { latitude: 5.473, longitude: 100.2465 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 11:30 - 23:00',
    score: 4.7,
    description: 'Bustling open-air food center offering char koay teow, satay skewers, grilled stingray, and fresh tropical fruit juices.',
  },
  {
    name: 'Batu Ferringhi Heritage Kopitiam',
    category: 'Food',
    plannerCategories: ['Food', 'Local Business'],
    interestTags: ['Food', 'Local Business'],
    formattedAddress: 'Jalan Batu Ferringhi, 11100 Batu Ferringhi, Penang, Malaysia',
    area: 'Batu Ferringhi',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.4715, longitude: 100.245 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 07:00 - 14:00',
    score: 4.6,
    description: 'Traditional morning kopitiam serving charcoal-toasted kaya butter toast, half-boiled kampung eggs, and aromatic Hainanese coffee.',
  },
  {
    name: 'Audi Dream Farm Balik Pulau',
    category: 'Nature',
    plannerCategories: ['Nature', 'Culture', 'Local Business'],
    interestTags: ['Nature', 'Culture', 'Local Business'],
    formattedAddress: 'Jalan Pulau Betong, 11000 Balik Pulau, Penang, Malaysia',
    area: 'Balik Pulau',
    durationMinutes: 75,
    budgetLevel: 'Low',
    location: { latitude: 5.319, longitude: 100.203 },
    phone: '+6012-406 9099',
    website: '',
    openingHours: 'Daily 09:00 - 18:00',
    score: 4.6,
    description: 'Rural family eco-farm in Balik Pulau featuring petting zoo animals, organic vegetable plots, sunflower gardens, and fresh farm dining.',
  },
  {
    name: 'Saanen Dairy Goat Farm Balik Pulau',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business'],
    interestTags: ['Nature', 'Local Business'],
    formattedAddress: '298 Mukim 1 Sungai Pinang, 11010 Balik Pulau, Penang, Malaysia',
    area: 'Balik Pulau',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.378, longitude: 100.212 },
    phone: '+6019-516 3017',
    website: '',
    openingHours: 'Daily 10:00 - 17:00',
    score: 4.7,
    description: 'Charming family-run goat farm where visitors can feed friendly dairy goats, taste fresh pasteurized goat milk, and try homemade goat milk ice cream.',
  },
  {
    name: 'Ghee Hup Nutmeg Factory & Plantation',
    category: 'Culture',
    plannerCategories: ['Culture', 'Nature', 'Local Business', 'Food'],
    interestTags: ['Culture', 'Nature', 'Local Business', 'Food'],
    formattedAddress: 'Bukit Prince of Wales, 11000 Balik Pulau, Penang, Malaysia',
    area: 'Balik Pulau',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.3582, longitude: 100.2285 },
    phone: '+6012-426 6422',
    website: '',
    openingHours: 'Daily 09:00 - 17:00',
    score: 4.7,
    description: 'Traditional hillside nutmeg plantation and processing cottage producing sweet nutmeg slices, therapeutic nutmeg oil, and fresh nutmeg juice.',
  },
  {
    name: 'Kim Laksa Balik Pulau (Nan Guang Coffee Shop)',
    category: 'Food',
    plannerCategories: ['Food', 'Culture', 'Local Business'],
    interestTags: ['Food', 'Culture', 'Local Business'],
    formattedAddress: 'Nan Guang Coffee Shop, Main Road, 11000 Balik Pulau, Penang, Malaysia',
    area: 'Balik Pulau',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.3524, longitude: 100.2366 },
    phone: '+6012-448 8177',
    website: '',
    openingHours: 'Wed-Sun 10:00 - 17:00',
    score: 4.8,
    description: 'Celebrated Balik Pulau coffee shop serving two styles of laksa: pungent spicy Assam Laksa and creamy coconut milk Siam Laksa.',
  },
  {
    name: 'Bao Sheng Durian Farm & Orchard',
    category: 'Food',
    plannerCategories: ['Food', 'Nature', 'Local Business'],
    interestTags: ['Food', 'Nature', 'Local Business'],
    formattedAddress: '150 Mukim 2 Sungai Pinang, 11010 Balik Pulau, Penang, Malaysia',
    area: 'Balik Pulau',
    durationMinutes: 75,
    budgetLevel: 'High',
    location: { latitude: 5.398, longitude: 100.219 },
    phone: '+6012-411 0600',
    website: '',
    openingHours: 'Daily 11:00 - 18:00 (Durian Season)',
    score: 4.7,
    description: 'Heritage organic durian estate overlooking the Malacca Strait, offering seasonal tasting sessions of Red Prawn, Musang King, and Black Thorn.',
  },
  {
    name: 'Balik Pulau Countryside Art Murals',
    category: 'Art',
    plannerCategories: ['Art', 'Nature', 'Culture'],
    interestTags: ['Art', 'Nature', 'Culture'],
    formattedAddress: 'Pekan Balik Pulau, 11000 Balik Pulau, Penang, Malaysia',
    area: 'Balik Pulau',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.3515, longitude: 100.2355 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.7,
    description: 'Large-scale rural wall murals by Russian artist Julia Volchkova celebrating local fishermen, martial artists, and silversmiths in village shophouses.',
  },
  {
    name: 'Pantai Pasir Panjang (Long Sand Beach)',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Mukim 9 Pulau Betong, 11000 Balik Pulau, Penang, Malaysia',
    area: 'Balik Pulau',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.302, longitude: 100.185 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.6,
    description: 'Tranquil secluded southwest coast beach with scenic fishing boat views, casuarina trees, and panoramic sunsets.',
  },
  {
    name: 'Penang Floating Mosque (Masjid Terapung Tanjung Bungah)',
    category: 'Culture',
    plannerCategories: ['Culture', 'Heritage', 'Nature'],
    interestTags: ['Culture', 'Heritage', 'Nature'],
    formattedAddress: 'Jalan Tanjung Bungah, 11200 Tanjung Bungah, Penang, Malaysia',
    area: 'Tanjung Bungah',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4697, longitude: 100.2762 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 06:00 - 21:00',
    score: 4.8,
    description: 'The first floating mosque built on stilts over the sea in Malaysia, featuring Middle Eastern and local architectural minarets.',
  },
  {
    name: 'Tanjung Bungah Beach Coastline',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Jalan Tanjung Bungah, 11200 Tanjung Bungah, Penang, Malaysia',
    area: 'Tanjung Bungah',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.466, longitude: 100.282 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.6,
    description: 'Peaceful northern coast beach known for watersports clubs, gentle ocean waves, and panoramic sea horizons.',
  },
  {
    name: 'Avatar Secret Garden (Tanjung Tokong Seafront)',
    category: 'Nature',
    plannerCategories: ['Nature', 'Culture', 'Local Business'],
    interestTags: ['Nature', 'Culture', 'Local Business'],
    formattedAddress: 'Jalan Tokong Thai Pak Koong, Tanjung Tokong, 10470 Penang, Malaysia',
    area: 'Tanjung Tokong',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.4635, longitude: 100.3075 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 08:00 - 00:00',
    score: 4.6,
    description: 'Enchanting illuminated coastal forest garden behind the Thai Pak Koong seaside temple, with colourful fibre-optic canopy lights.',
  },
  {
    name: 'Straits Quay Marina & Coastal Promenade',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business', 'Food'],
    interestTags: ['Nature', 'Local Business', 'Food'],
    formattedAddress: 'Jalan Seri Tanjung Pinang, Tanjung Tokong, 10470 Penang, Malaysia',
    area: 'Tanjung Tokong',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4578, longitude: 100.313 },
    phone: '+604-891 8000',
    website: '',
    openingHours: 'Daily 10:00 - 22:00',
    score: 4.7,
    description: 'Penang\'s premier seafront marina retail and dining promenade with yacht berths, breezy waterfront cafes, and arts market stalls.',
  },
  {
    name: 'Dharmikarama Burmese Temple',
    category: 'Culture',
    plannerCategories: ['Culture', 'Heritage', 'Art'],
    interestTags: ['Culture', 'Heritage', 'Art'],
    formattedAddress: '24 Lorong Burma, Pulau Tikus, 10250 George Town, Penang, Malaysia',
    area: 'Pulau Tikus',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.4312, longitude: 100.3142 },
    phone: '+604-226 9350',
    website: '',
    openingHours: 'Daily 08:00 - 18:00',
    score: 4.8,
    description: 'Historic Burmese temple founded in 1803 featuring a grand golden stupa, wishing pond, shrine of Arahant Upagutta, and historical murals.',
  },
  {
    name: 'Wat Chayamangkalaram (Reclining Buddha Temple)',
    category: 'Culture',
    plannerCategories: ['Culture', 'Heritage', 'Art'],
    interestTags: ['Culture', 'Heritage', 'Art'],
    formattedAddress: '17 Lorong Burma, Pulau Tikus, 10250 George Town, Penang, Malaysia',
    area: 'Pulau Tikus',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4316, longitude: 100.3144 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 08:00 - 17:30',
    score: 4.8,
    description: 'Renowned Thai Buddhist temple housing a colossal 33-metre gold-plated reclining Buddha statue and colourful mythical dragon guards.',
  },
  {
    name: 'Arulmigu Balathandayuthapani Temple (Waterfall Hilltop Temple)',
    category: 'Culture',
    plannerCategories: ['Culture', 'Heritage', 'Nature'],
    interestTags: ['Culture', 'Heritage', 'Nature'],
    formattedAddress: '17 Jalan Kebun Bunga, George Town, 10350 Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 75,
    budgetLevel: 'Low',
    location: { latitude: 5.4338, longitude: 100.2917 },
    phone: '+604-229 0777',
    website: '',
    openingHours: 'Daily 06:00 - 21:00',
    score: 4.8,
    description: 'Magnificent hilltop Hindu temple complex reached via 513 steps with sweeping views over George Town and focal point of Thaipusam.',
  },
  {
    name: 'Snake Temple (Ban Ka Lan Temple)',
    category: 'Culture',
    plannerCategories: ['Culture', 'Heritage'],
    interestTags: ['Culture', 'Heritage'],
    formattedAddress: 'Jalan Sultan Azlan Shah, Bayan Lepas, 11900 Penang, Malaysia',
    area: 'Bayan Lepas',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.3138, longitude: 100.2853 },
    phone: '+604-643 7273',
    website: '',
    openingHours: 'Daily 08:00 - 18:00',
    score: 4.6,
    description: 'Unique 1850 Taoist temple dedicated to Master Chor Soo Kong, famous for live green pit vipers resting peacefully around altars and incense burners.',
  },
  {
    name: 'Penang War Museum',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Nature'],
    interestTags: ['Heritage', 'Culture', 'Nature'],
    formattedAddress: 'Lot 1350 Mukim 12, Jalan Batu Maung, 11960 Bayan Lepas, Penang, Malaysia',
    area: 'Bayan Lepas',
    durationMinutes: 90,
    budgetLevel: 'Medium',
    location: { latitude: 5.2814, longitude: 100.2886 },
    phone: '+604-626 5142',
    website: 'https://penangwarmuseum.com/',
    openingHours: 'Daily 09:00 - 18:00',
    score: 4.6,
    description: 'Sprawling historical British coastal fortress and battery built in the 1930s on Bukit Maung, featuring underground tunnels, bunkers, and artillery.',
  },
  {
    name: 'Minor Basilica of St. Anne',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art'],
    interestTags: ['Heritage', 'Culture', 'Art'],
    formattedAddress: 'Jalan Kulim, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.3533, longitude: 100.4789 },
    phone: '+604-538 6405',
    website: 'https://stannebm.org/',
    openingHours: 'Daily 06:30 - 21:00',
    score: 4.9,
    culturalTask: {
      title: 'Basilica Architecture Discovery',
      description: 'Photograph the gothic facade of St. Anne Basilica and the historic 1888 hillside chapel.',
      rewardPoints: 110,
    },
    description: 'Historic Catholic pilgrimage site elevated to Minor Basilica status, featuring Gothic architecture, stained glass, and the 1888 Old Shrine.',
  },
  {
    name: 'Cherok Tokun Nature Park & BM Hill Trail',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Jalan Kolam, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 90,
    budgetLevel: 'Low',
    location: { latitude: 5.3582, longitude: 100.4908 },
    phone: '+604-530 1800',
    website: '',
    openingHours: 'Daily 07:00 - 19:00',
    score: 4.7,
    description: 'Lush forest reserve with tranquil walking trails, fresh mountain streams, canopy trees, and the scenic hiking path up BM Hill peak.',
  },
  {
    name: 'Mengkuang Dam Lakeside Park',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business'],
    interestTags: ['Nature', 'Local Business'],
    formattedAddress: 'Mukim 18, Mengkuang, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 75,
    budgetLevel: 'Low',
    location: { latitude: 5.4012, longitude: 100.493 },
    phone: '+604-500 1200',
    website: '',
    openingHours: 'Daily 07:00 - 19:00',
    score: 4.8,
    description: 'Serene mainland Penang reservoir park framed by green hill peaks, expansive lake scenery, and a popular jogging trail.',
  },
  {
    name: 'Bukit Juru Nature Trail',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Kuala Juru, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 75,
    budgetLevel: 'Low',
    location: { latitude: 5.334, longitude: 100.418 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 07:00 - 19:00',
    score: 4.6,
    description: 'Scenic hilltop coastal hiking trail in Seberang Perai with panoramic views of the Penang Second Bridge, mangrove forests, and fishing boats.',
  },
  {
    name: 'Frog Hill (Bukit Katak) Scenic Lakes',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Kampung Ladang Toh Allah, 14400 Tasek Gelugor, Penang, Malaysia',
    area: 'Butterworth',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.441, longitude: 100.485 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 07:00 - 18:30',
    score: 4.7,
    description: 'Spectacular abandoned quarry site featuring vivid turquoise-green mineral lakes and red clay ridges reminiscent of Jiuzhaigou.',
  },
  {
    name: 'Robina Eco Park Butterworth (Pantai Bersih)',
    category: 'Nature',
    plannerCategories: ['Nature'],
    interestTags: ['Nature'],
    formattedAddress: 'Jalan Robina, Taman Robina, 13050 Butterworth, Penang, Malaysia',
    area: 'Butterworth',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.459, longitude: 100.381 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.6,
    description: 'Revitalized seafront coastal park overlooking Penang Island with sunset walking piers, sea breeze promenades, and beach recreation.',
  },
  {
    name: 'Restoran BM Yam Rice',
    category: 'Food',
    plannerCategories: ['Food', 'Local Business', 'Culture'],
    interestTags: ['Food', 'Local Business', 'Culture'],
    formattedAddress: '7 Jalan Murthy, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.3644, longitude: 100.4608 },
    phone: '+604-530 6826',
    website: '',
    openingHours: 'Daily 09:00 - 15:00',
    score: 4.8,
    description: 'Famous Bukit Mertajam fragrant yam rice paired with salted mustard greens pork rib soup, tender offal, and spicy chili dip.',
  },
  {
    name: 'Restoran BM Cup Rice (Danby Cup Rice)',
    category: 'Food',
    plannerCategories: ['Food', 'Local Business'],
    interestTags: ['Food', 'Local Business'],
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.3639, longitude: 100.4608 },
    phone: '+6012-421 8833',
    website: '',
    openingHours: 'Daily 08:00 - 14:00',
    score: 4.7,
    description: 'Iconic vintage BM cup rice drenched in rich roasted pork gravy with tender char siew in a bustling town shophouse.',
  },
  {
    name: 'BM Famous Duck Egg Char Koay Teow',
    category: 'Food',
    plannerCategories: ['Food', 'Local Business'],
    interestTags: ['Food', 'Local Business'],
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.3635, longitude: 100.4602 },
    phone: '+6016-443 2819',
    website: '',
    openingHours: 'Daily 19:00 - 23:30',
    score: 4.9,
    description: 'Famous charcoal-fried char koay teow cooked with rich creamy duck egg, fresh cockles, and fragrant wok hei on Jalan Pasar.',
  },
  {
    name: 'BM Rojak Orang Hitam Putih',
    category: 'Food',
    plannerCategories: ['Food', 'Local Business'],
    interestTags: ['Food', 'Local Business'],
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 30,
    budgetLevel: 'Low',
    location: { latitude: 5.3641, longitude: 100.4615 },
    phone: '+6012-475 2288',
    website: '',
    openingHours: 'Daily 11:30 - 18:30',
    score: 4.8,
    description: 'Renowned BM fruit and crispy fritter rojak tossed in thick, aromatic black shrimp paste and crushed roasted peanuts.',
  },
  {
    name: 'Sentosa Food Court BM',
    category: 'Food',
    plannerCategories: ['Food', 'Local Business'],
    interestTags: ['Food', 'Local Business'],
    formattedAddress: 'Jalan Sentosa, Taman Sentosa, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.3488, longitude: 100.4722 },
    phone: '+604-539 8888',
    website: '',
    openingHours: 'Daily 17:00 - 00:00',
    score: 4.7,
    description: 'Bustling evening food court in Taman Sentosa featuring over 40 hawker stalls serving BBQ stingray, satay, fried oyster omelette, and claypot noodles.',
  },
  {
    name: 'Pekan Bukit Mertajam Old Market Street',
    category: 'Culture',
    plannerCategories: ['Culture', 'Food', 'Local Business'],
    interestTags: ['Culture', 'Food', 'Local Business'],
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.3638, longitude: 100.4612 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 06:00 - 18:00',
    score: 4.7,
    description: 'Heart of BM town featuring traditional old-style dry and wet markets, Chinese herbal medicine halls, tea merchants, and street hawkers.',
  },
  {
    name: 'Penang Bird Park Seberang Jaya',
    category: 'Nature',
    plannerCategories: ['Nature', 'Local Business'],
    interestTags: ['Nature', 'Local Business'],
    formattedAddress: 'Jalan Todak, Seberang Jaya, 13700 Butterworth, Penang, Malaysia',
    area: 'Butterworth',
    durationMinutes: 90,
    budgetLevel: 'Medium',
    location: { latitude: 5.3958, longitude: 100.3981 },
    phone: '+604-399 1899',
    website: '',
    openingHours: 'Daily 09:00 - 18:00',
    score: 4.6,
    description: 'First and largest bird park in Malaysia, housing over 300 bird species with walk-in aviaries, lotus ponds, and flamingos.',
  },
  {
    name: 'Butterworth Art Walk',
    category: 'Art',
    plannerCategories: ['Art', 'Culture', 'Heritage'],
    interestTags: ['Art', 'Culture', 'Heritage'],
    formattedAddress: '1 Lorong Bagan Luar 1, 12000 Butterworth, Penang, Malaysia',
    area: 'Butterworth',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4121, longitude: 100.3664 },
    phone: '+604-332 5000',
    website: '',
    openingHours: 'Daily 24 Hours',
    score: 4.6,
    description: 'Vibrant outdoor alleyway art exhibition showcasing interactive 3D murals depicting Butterworth\'s agricultural, port, and cultural history.',
  },
  {
    name: 'Tow Boo Kong Temple (Nine Emperor Gods)',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture', 'Art'],
    interestTags: ['Heritage', 'Culture', 'Art'],
    formattedAddress: 'Jalan Raja Uda, 12300 Butterworth, Penang, Malaysia',
    area: 'Butterworth',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.4336, longitude: 100.3844 },
    phone: '+604-331 3318',
    website: '',
    openingHours: 'Daily 07:00 - 21:00',
    score: 4.8,
    description: 'One of the grandest Taoist temple complexes in Malaysia, famed for its massive carved stone archway, golden dragon pillars, and Nine Emperor Gods festival.',
  },
  {
    name: 'Sree Maha Mariamman Temple Butterworth',
    category: 'Heritage',
    plannerCategories: ['Heritage', 'Culture'],
    interestTags: ['Heritage', 'Culture'],
    formattedAddress: 'Jalan Bagh, 12000 Butterworth, Penang, Malaysia',
    area: 'Butterworth',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.4019, longitude: 100.3688 },
    phone: '+604-200 0000',
    website: '',
    openingHours: 'Daily 06:00 - 20:30',
    score: 4.7,
    description: 'Historic Dravidian Hindu temple in Butterworth dating back to the 19th century, featuring a multi-tiered colourful Rajagopuram.',
  },

  // KUALA LUMPUR & SELANGOR
  {
    name: 'Central Market (Pasar Seni)',
    category: 'Heritage',
    formattedAddress: 'Jalan Hang Kasturi, City Centre, 50050 Kuala Lumpur, Malaysia',
    area: 'Kuala Lumpur',
    durationMinutes: 75,
    budgetLevel: 'Free',
    location: { latitude: 3.1453, longitude: 101.6953 },
    phone: '+603-2031 0399',
    openingHours: 'Mon-Sun 10:00-22:00',
    score: 4.8,
    description: 'Iconic 1888 Art Deco cultural landmark hosting Malaysian handicrafts, batik studios, Wau kite artisans, and traditional performances.',
  },
  {
    name: 'Batu Caves Lord Murugan Shrine',
    category: 'Heritage',
    formattedAddress: 'Gombak, 68100 Batu Caves, Selangor, Malaysia',
    area: 'Selangor',
    durationMinutes: 90,
    budgetLevel: 'Free',
    location: { latitude: 3.2379, longitude: 101.6840 },
    phone: '+603-6189 6284',
    openingHours: 'Mon-Sun 06:00-21:00',
    score: 4.8,
    culturalTask: {
      title: 'Cathedral Cave Step Ascent',
      description: 'Climb the 272 rainbow steps and photograph the limestone cathedral cave interior.',
      rewardPoints: 130,
    },
    description: 'Limestone hill comprising three major caves, world-renowned 140-ft golden Lord Murugan statue, and 272 colourful rainbow steps.',
  },

  // KELANTAN & TERENGGANU
  {
    name: 'Pasar Besar Siti Khadijah',
    category: 'Heritage',
    formattedAddress: 'Jalan Buluh Kubu, Bandar Kota Bharu, 15000 Kota Bharu, Kelantan, Malaysia',
    area: 'Kota Bharu',
    durationMinutes: 75,
    budgetLevel: 'Low',
    location: { latitude: 6.1287, longitude: 102.2392 },
    phone: '+609-748 2140',
    openingHours: 'Mon-Sun 07:00-18:00',
    score: 4.8,
    culturalTask: {
      title: 'Octagonal Market Geometry & Kuih Akok',
      description: 'Photograph the colourful central octagonal produce hall and sample warm Kuih Akok.',
      rewardPoints: 130,
    },
    description: 'Iconic 4-storey octagonal central market in Kota Bharu operated mostly by female traders, vibrant with local spices and traditional songket.',
  },
  {
    name: 'Masjid Kristal',
    category: 'Heritage',
    formattedAddress: 'Pulau Wan Man, 21000 Kuala Terengganu, Terengganu, Malaysia',
    area: 'Kuala Terengganu',
    durationMinutes: 60,
    budgetLevel: 'Free',
    location: { latitude: 5.3224, longitude: 103.1189 },
    phone: '+609-627 8888',
    openingHours: 'Mon-Sun 06:00-22:00',
    score: 4.8,
    culturalTask: {
      title: 'Crystal Reflection Snapshot',
      description: 'Photograph the gleaming crystal and glass domes reflecting over the Terengganu River.',
      rewardPoints: 120,
    },
    description: 'Magnificent grand mosque built from steel, glass, and crystal on Pulau Wan Man overlooking the scenic Terengganu River.',
  },
  {
    name: 'Borneo Cultures Museum',
    category: 'Culture',
    formattedAddress: 'Jalan Tun Abang Haji Openg, 93000 Kuching, Sarawak, Malaysia',
    area: 'Kuching',
    durationMinutes: 120,
    budgetLevel: 'Medium',
    location: { latitude: 1.5546, longitude: 110.3421 },
    phone: '+6082-536 788',
    openingHours: 'Mon-Fri 09:00-16:45, Sat-Sun 09:30-16:30',
    score: 4.9,
    culturalTask: {
      title: 'Indigenous Tribal Arts Study',
      description: 'Explore Level 3 or 4 and photograph one traditional Dayak craft or textile heirloom.',
      rewardPoints: 150,
    },
    description: 'Iconic 5-storey museum and the second largest in Southeast Asia, housing over 1,000 Borneo cultural artefacts.',
  },
];

const sampleReviewers = [
  'Tan Mei Ling',
  'Hafiz Ridzuan',
  'Sarah Jenkins',
  'Bernard Lim',
  'Chloe Dupont',
  'Kavitha Nair',
  'Chen Wei Ming',
  'Ahmad Faiz',
];

async function seed() {
  console.log(`Starting Firestore sync for ${places.length} curated venues...`);

  let vendorCount = 0;
  let placeCount = 0;
  let reviewCount = 0;

  for (const place of places) {
    const name = place.name.trim();
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
    const vendorId = `vendor_${slug}`;
    const placeId = `place_${slug}`;
    const emailSlug = slug.replace(/_/g, '');
    const vendorEmail = `${emailSlug}@myheritage.my`;

    // 1. Set Vendor
    const tags = place.interestTags || place.plannerCategories || [place.category || 'Heritage'];
    await db.collection('vendors').doc(vendorId).set({
      uid: vendorId,
      vendorId: vendorId,
      businessName: name,
      displayName: name,
      ownerName: `${name} Management`,
      email: vendorEmail,
      phone: place.phone || '+604-500 0000',
      category: place.category || 'Heritage',
      area: place.area || 'Malaysia',
      state: 'penang',
      stateName: 'Penang',
      stateId: 'penang',
      interestTags: tags,
      tags: tags,
      formattedAddress: place.formattedAddress || place.area,
      location: place.location || { latitude: 5.4, longitude: 100.3 },
      role: 'vendor',
      status: 'active',
      vendorStatus: 'verified',
      score: place.score || 4.8,
      website: place.website || '',
      openingHours: place.openingHours || 'Mon-Sun 09:00-18:00',
      description: place.description || '',
      updatedAt: FieldValue.serverTimestamp(),
      createdAt: FieldValue.serverTimestamp(),
    }, { merge: true });
    vendorCount++;

    // 2. Set Place
    await db.collection('places').doc(placeId).set({
      placeId: placeId,
      vendorId: vendorId,
      name: name,
      category: place.category || 'Heritage',
      area: place.area || 'Malaysia',
      stateId: 'penang',
      stateName: 'Penang',
      interestTags: tags,
      plannerCategories: tags,
      tags: tags,
      formattedAddress: place.formattedAddress || place.area,
      location: place.location || { latitude: 5.4, longitude: 100.3 },
      score: place.score || 4.8,
      durationMinutes: place.durationMinutes || 60,
      budgetLevel: place.budgetLevel || 'Low',
      phone: place.phone || '+604-500 0000',
      website: place.website || '',
      openingHours: place.openingHours || 'Mon-Sun 09:00-18:00',
      description: place.description || '',
      culturalTask: place.culturalTask || null,
      isVerified: true,
      isActive: true,
      status: 'active',
      trustLabel: 'High Trust',
      updatedAt: FieldValue.serverTimestamp(),
      createdAt: FieldValue.serverTimestamp(),
    }, { merge: true });
    placeCount++;

    // 3. Seed 3-4 Valid Reviews
    const validReviews = [
      {
        rating: 5,
        comment: `Outstanding experience visiting ${name}! The authentic atmosphere, friendly hospitality, and deep cultural heritage make it a top must-visit spot in ${place.area}.`,
      },
      {
        rating: 5,
        comment: `Highly recommended! Excellent quality, vibrant local atmosphere, and thoroughly enjoyable visit. Don't forget to take photos.`,
      },
      {
        rating: 4,
        comment: `Great stop during our tour of ${place.area}. Clean surroundings, authentic offerings, and very informative.`,
      },
    ];

    for (let i = 0; i < validReviews.length; i++) {
      const reviewDocId = `rev_${slug}_valid_${i + 1}`;
      const reviewer = sampleReviewers[(vendorCount + i) % sampleReviewers.length];
      await db.collection('reviews').doc(reviewDocId).set({
        reviewId: reviewDocId,
        placeId: placeId,
        vendorId: vendorId,
        placeName: name,
        travelerName: reviewer,
        rating: validReviews[i].rating,
        comment: validReviews[i].comment,
        status: 'valid',
        mlDecision: 'valid',
        mlSuspiciousProbability: 0.04,
        mlRatingMismatch: false,
        flagReasons: [],
        createdAt: Timestamp.fromDate(new Date(Date.now() - (i + 1) * 86400000 * 3)),
      }, { merge: true });
      reviewCount++;
    }

    // 4. Seed select flagged reviews for testing ML Moderation
    if (vendorCount % 3 === 0) {
      const flaggedDocId = `rev_${slug}_flagged_1`;
      await db.collection('reviews').doc(flaggedDocId).set({
        reviewId: flaggedDocId,
        placeId: placeId,
        vendorId: vendorId,
        placeName: name,
        travelerName: 'SpamBot_Promo',
        rating: 5,
        comment: `Check out cheap discounts and free promo vouchers at http://super-discount-tourist-deals.xyz/claim now! Best place in ${place.area}!`,
        status: 'flagged',
        mlDecision: 'flagged',
        mlSuspiciousProbability: 0.96,
        mlRatingMismatch: false,
        flagReasons: ['Promotional spam URL link detected'],
        flagReason: 'Promotional spam URL link detected',
        createdAt: Timestamp.fromDate(new Date(Date.now() - 86400000)),
      }, { merge: true });
      reviewCount++;
    }
  }

  console.log(`Successfully synced directly to Firebase:`);
  console.log(`- ${vendorCount} Vendors in collection('vendors')`);
  console.log(`- ${placeCount} Places in collection('places')`);
  console.log(`- ${reviewCount} Reviews in collection('reviews')`);
}

seed().then(() => {
  process.exit(0);
}).catch(err => {
  console.error('Seeding error:', err);
  process.exit(1);
});
