'use strict';

const { initializeApp, cert } = require('firebase-admin/app');
const { getFirestore, FieldValue, Timestamp } = require('firebase-admin/firestore');

const serviceAccount = require('./serviceAccountKey.json');

initializeApp({
  credential: cert(serviceAccount),
});

const db = getFirestore();

// All Curated Malaysian Vendors & Places
const places = [
  // PENANG (GEORGE TOWN, AIR ITAM, TELUK BAHANG, BALIK PULAU, BUKIT MERTAJAM, BUTTERWORTH)
  {
    name: 'Pinang Peranakan Mansion',
    category: 'Heritage',
    formattedAddress: '29 Church Street, 10200 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 75,
    budgetLevel: 'Medium',
    location: { latitude: 5.41758, longitude: 100.34262 },
    phone: '+604-264 2929',
    website: 'https://www.pinangperanakanmansion.com.my/',
    openingHours: 'Mon-Sun 09:30-17:30',
    score: 4.8,
    culturalTask: {
      title: 'Peranakan Heritage Discovery',
      description: 'Photograph one traditional Baba Nyonya antique or architectural carving and learn about Penang Peranakan customs.',
      rewardPoints: 120,
    },
    description: 'A stately recreation of a rich 19th-century Baba Nyonya residence showcasing over 1,000 antique Peranakan heirlooms, customs and ornate architecture.',
  },
  {
    name: 'Cheong Fatt Tze - The Blue Mansion',
    category: 'Heritage',
    formattedAddress: '14 Leith Street, 10200 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 75,
    budgetLevel: 'High',
    location: { latitude: 5.42157, longitude: 100.33407 },
    phone: '+604-262 0006',
    website: 'https://www.cheongfatttzemansion.com/',
    openingHours: 'Mon-Sun 11:00-18:00',
    score: 4.7,
    culturalTask: {
      title: 'Indigo Architectural Snapshot',
      description: 'Photograph the iconic indigo courtyard and identify one unique Feng Shui element.',
      rewardPoints: 130,
    },
    description: 'Award-winning UNESCO-conserved 1890s courtyard mansion famous for its striking indigo blue walls, Art Nouveau stained glass, and Chinese master craft.',
  },
  {
    name: 'Leong San Tong Khoo Kongsi',
    category: 'Heritage',
    formattedAddress: '18 Cannon Square, 10200 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4165, longitude: 100.3373 },
    phone: '+604-261 4609',
    website: 'https://www.khookongsi.com.my/',
    openingHours: 'Mon-Sun 09:00-17:00',
    score: 4.9,
    culturalTask: {
      title: 'Clan Architecture Study',
      description: 'Photograph the intricate granite stone carvings or ornate roof dragons at Khoo Kongsi.',
      rewardPoints: 140,
    },
    description: 'The grandest Chinese clan house in Malaysia, renowned for its opulent stone and wood carvings, dragon pillars, and clan lineage museum.',
  },
  {
    name: 'Wonderfood Museum Penang',
    category: 'Culture',
    formattedAddress: '49 Beach Street, 10200 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4163, longitude: 100.3411 },
    phone: '+604-262 9504',
    website: 'https://www.facebook.com/Wonderfoodmuseum/',
    openingHours: 'Mon-Sun 09:00-18:00',
    score: 4.6,
    culturalTask: {
      title: 'Giant Hawker Food Snap',
      description: 'Pose alongside giant replica dishes of Laksa, Cendol, or Roti Canai to document Malaysian street food heritage.',
      rewardPoints: 100,
    },
    description: 'Vibrant interactive museum displaying hyper-realistic giant replicas of Malaysian cuisines, traditional street food carts, and colonial banquet dioramas.',
  },
  {
    name: 'Fort Cornwallis',
    category: 'Heritage',
    formattedAddress: 'Jalan Tun Syed Sheh Barakbah, 10200 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.4208, longitude: 100.3441 },
    phone: '+604-261 0260',
    website: 'https://www.thefortcornwallis.com/',
    openingHours: 'Mon-Sun 08:00-23:00',
    score: 4.5,
    culturalTask: {
      title: 'Colonial Bastion History',
      description: 'Locate the historic Seri Rambai Cannon and photograph the harbour bastion.',
      rewardPoints: 110,
    },
    description: 'Largest standing British fortress in Malaysia, constructed in 1786 by Captain Francis Light with lighthouse, chapel, and historical artillery.',
  },
  {
    name: 'Chew Jetty',
    category: 'Culture',
    formattedAddress: 'Chew Jetty, Weld Quay, 10300 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 45,
    budgetLevel: 'Free',
    location: { latitude: 5.4128, longitude: 100.3398 },
    phone: '+604-263 6050',
    openingHours: 'Mon-Sun 09:00-21:00',
    score: 4.6,
    culturalTask: {
      title: 'Waterfront Clan Settlement Walk',
      description: 'Photograph the stilt wooden walkway overlooking the Penang Strait and visit the waterfront temple shrine.',
      rewardPoints: 100,
    },
    description: 'The most famous of Penang\'s historic clan stilt settlements built in the 19th century by immigrant Chinese dock workers.',
  },
  {
    name: 'Hin Bus Depot',
    category: 'Art',
    formattedAddress: '31A Jalan Gurdwara, 10300 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Free',
    location: { latitude: 5.4124, longitude: 100.3297 },
    phone: '+604-218 9004',
    website: 'https://hinbusdepot.com/',
    openingHours: 'Mon-Fri 12:00-19:00, Sat-Sun 11:00-19:00',
    score: 4.7,
    culturalTask: {
      title: 'Artisan Depot Mural Explorer',
      description: 'Explore the open art courtyard and photograph Ernest Zacharevic murals or weekend artisan crafts.',
      rewardPoints: 110,
    },
    description: 'A thriving community art space and gallery set within a restored 1940s Art Deco bus depot, hosting murals, sculptures, cafes, and weekend artisan markets.',
  },
  {
    name: 'Jawi House Cafe Gallery',
    category: 'Food',
    formattedAddress: '85 Armenian Street, 10200 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4152, longitude: 100.3364 },
    phone: '+604-261 3680',
    website: 'https://jawihouse.com/',
    openingHours: 'Wed-Mon 11:00-21:30',
    score: 4.7,
    culturalTask: {
      title: 'Jawi Peranakan Spice Heritage',
      description: 'Taste authentic Jawi Peranakan Nasi Lemuni or Herbal Rice and snap a photo of the heritage dining interior.',
      rewardPoints: 110,
    },
    description: 'Culinary gallery and heritage restaurant celebrating Jawi Peranakan gastronomy, featuring Nasi Lemuni, herbal curries, and antique gallery displays.',
  },
  {
    name: 'ChinaHouse Penang',
    category: 'Food',
    formattedAddress: '153 Beach Street & 183B Victoria Street, 10300 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4148, longitude: 100.3394 },
    phone: '+604-263 7299',
    website: 'https://www.chinahouse.com.my/',
    openingHours: 'Mon-Sun 09:00-00:00',
    score: 4.7,
    culturalTask: {
      title: 'Longest Shophouse Art & Cake Walk',
      description: 'Walk through the 400-ft connected heritage shophouse compound and photograph the iconic cake table display.',
      rewardPoints: 100,
    },
    description: 'Traditional heritage compound made of three linked heritage shophouses with an open courtyard, plunge pool, library, art gallery, and over 30 varieties of daily cakes.',
  },
  {
    name: 'Tek Sen Restaurant',
    category: 'Food',
    formattedAddress: '18 Carnarvon Street, 10100 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.4172, longitude: 100.3355 },
    phone: '+6012-981 5117',
    website: 'https://www.facebook.com/TekSenRestaurant/',
    openingHours: 'Wed-Mon 12:00-14:30, 18:00-20:30',
    score: 4.8,
    culturalTask: {
      title: 'Double Cooked Pork Belly Feast',
      description: 'Sample Tek Sen\'s famous double-cooked pork belly with chili padi and dark soy sauce.',
      rewardPoints: 95,
    },
    description: 'Michelin Bib Gourmand heritage Cantonese and Teochew zi char restaurant established in 1965, famous for caramelized roasted pork, Assam fish, and stir-fried potato leaves.',
  },
  {
    name: 'Hameediyah Restaurant',
    category: 'Food',
    formattedAddress: '164A Campbell Street, 10100 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.4191, longitude: 100.3332 },
    phone: '+604-261 1095',
    website: 'https://hameediyah.my/',
    openingHours: 'Mon-Sun 10:00-22:00',
    score: 4.8,
    culturalTask: {
      title: 'Oldest Nasi Kandar Feast',
      description: 'Order signature Murtabak or Duck Rendang with spiced kuah campur and photograph the historic brass pots.',
      rewardPoints: 100,
    },
    description: 'Oldest running Nasi Kandar restaurant in Malaysia established in 1907, world-famous for lamb shank briyani, crispy murtabak, and spiced kuah campur.',
  },
  {
    name: 'Penang Road Famous Teochew Chendul',
    category: 'Food',
    formattedAddress: '27 & 29 Lebuh Keng Kwee, 10100 George Town, Penang, Malaysia',
    area: 'George Town',
    durationMinutes: 30,
    budgetLevel: 'Low',
    location: { latitude: 5.4171, longitude: 100.3308 },
    phone: '+604-262 6002',
    website: 'https://www.chendul.my/',
    openingHours: 'Mon-Sun 10:30-19:00',
    score: 4.7,
    culturalTask: {
      title: 'Heritage Street Chendul Tasting',
      description: 'Enjoy a refreshing bowl of shaved ice Chendul with red beans and santan by Lebuh Keng Kwee street.',
      rewardPoints: 90,
    },
    description: 'Legendary roadside dessert stall founded in 1936 serving signature Teochew chendul with fresh coconut milk, pandan jelly noodles, and fragrant Gula Melaka syrup.',
  },
  {
    name: 'Kek Lok Si Temple',
    category: 'Heritage',
    formattedAddress: 'Tingkat Lembah Ria 1, 11500 Air Itam, Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 90,
    budgetLevel: 'Low',
    location: { latitude: 5.3995, longitude: 100.2736 },
    phone: '+604-828 3317',
    website: 'https://kekloksitemple.com/',
    openingHours: 'Mon-Sun 08:30-17:30',
    score: 4.9,
    culturalTask: {
      title: 'Pagoda of Ten Thousand Buddhas',
      description: 'Climb the 7-tier Pagoda combining Chinese, Thai, and Burmese architectural tiers and photograph the view.',
      rewardPoints: 140,
    },
    description: 'Largest Buddhist temple complex in Malaysia, featuring the 7-tier Ban Po Thar Pagoda, 30-metre bronze Kuan Yin statue, and scenic mountain views.',
  },
  {
    name: 'The Habitat Penang Hill',
    category: 'Nature',
    formattedAddress: 'Bukit Bendera, 11300 Penang, Malaysia',
    area: 'Air Itam',
    durationMinutes: 120,
    budgetLevel: 'High',
    location: { latitude: 5.4243, longitude: 100.2687 },
    phone: '+604-826 7677',
    website: 'https://thehabitat.my/',
    openingHours: 'Mon-Sun 09:00-19:00',
    score: 4.8,
    culturalTask: {
      title: 'Curtis Crest Rainforest Canopy Walk',
      description: 'Walk along the tree canopy bridge and Curtis Crest 360 platform in the 130-million-year-old rainforest.',
      rewardPoints: 150,
    },
    description: 'World-class eco-tourism rainforest reserve inside the UNESCO Biosphere Reserve on Penang Hill, featuring Curtis Crest 360 treetop walkway and nature trails.',
  },

  // BUKIT MERTAJAM (BM)
  {
    name: 'Sentosa Food Court BM',
    category: 'Food',
    formattedAddress: 'Jalan Sentosa, Taman Sentosa, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 60,
    budgetLevel: 'Low',
    location: { latitude: 5.3488, longitude: 100.4722 },
    phone: '+604-539 8888',
    openingHours: 'Mon-Sun 17:00-00:00',
    score: 4.7,
    culturalTask: {
      title: 'Sentosa Evening Hawker Food Feast',
      description: 'Sample authentic local street food and photograph your dinner spread at Sentosa Food Court.',
      rewardPoints: 80,
    },
    description: 'Bustling evening food court in Taman Sentosa featuring over 40 hawker stalls serving BBQ stingray, satay, fried oyster omelette, and claypot noodles.',
  },
  {
    name: 'Restoran BM Yam Rice',
    category: 'Food',
    formattedAddress: '7 Jalan Murthy, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.3644, longitude: 100.4611 },
    phone: '+604-530 6826',
    openingHours: 'Mon-Sun 09:00-15:00',
    score: 4.8,
    culturalTask: {
      title: 'Legendary Yam Rice Tasting',
      description: 'Taste authentic BM Yam Rice with salted vegetable soup and take a photo of the signature dish.',
      rewardPoints: 90,
    },
    description: 'Legendary Bukit Mertajam yam rice served with hot salted mustard green pork soup, tender offal, and spicy chili dip.',
  },
  {
    name: 'Restoran BM Cup Rice (Danby Cup Rice)',
    category: 'Food',
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.3639, longitude: 100.4608 },
    phone: '+6012-421 8833',
    openingHours: 'Mon-Sun 08:00-14:00',
    score: 4.7,
    culturalTask: {
      title: 'Heritage Cup Rice Experience',
      description: 'Enjoy the classic BM cup rice and capture the vintage street ambience.',
      rewardPoints: 85,
    },
    description: 'Iconic vintage BM cup rice drenched in rich roasted pork gravy with tender char siew.',
  },
  {
    name: 'BM Famous Duck Egg Char Koay Teow',
    category: 'Food',
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.3635, longitude: 100.4602 },
    phone: '+6016-443 2819',
    openingHours: 'Mon-Sun 19:00-23:30',
    score: 4.9,
    culturalTask: {
      title: 'Duck Egg Wok Hei Snap',
      description: 'Order the signature duck egg Char Koay Teow and photograph the master stir-frying with charcoal wok hei.',
      rewardPoints: 95,
    },
    description: 'Famous charcoal-fried char koay teow cooked with rich creamy duck egg, fresh cockles, and fragrant wok hei.',
  },
  {
    name: 'BM Rojak Orang Hitam Putih',
    category: 'Food',
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 30,
    budgetLevel: 'Low',
    location: { latitude: 5.3641, longitude: 100.4615 },
    phone: '+6012-475 2288',
    openingHours: 'Mon-Sun 11:30-18:30',
    score: 4.8,
    culturalTask: {
      title: 'Orang Hitam Putih Rojak Tasting',
      description: 'Enjoy the signature Bukit Mertajam shrimp paste rojak topped with crushed toasted peanuts.',
      rewardPoints: 80,
    },
    description: 'Renowned BM fruit and fritter rojak tossed in thick, aromatic black shrimp paste and crushed peanuts.',
  },
  {
    name: 'Minor Basilica of St. Anne',
    category: 'Heritage',
    formattedAddress: 'Jalan Kulim, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 60,
    budgetLevel: 'Free',
    location: { latitude: 5.3533, longitude: 100.4789 },
    phone: '+604-538 6405',
    website: 'https://stannebm.org/',
    openingHours: 'Mon-Sun 06:30-21:00',
    score: 4.9,
    culturalTask: {
      title: 'Basilica Architecture Discovery',
      description: 'Photograph the gothic facade of St. Anne Basilica and the historic 1888 hillside chapel.',
      rewardPoints: 110,
    },
    description: 'Historic Catholic pilgrimage site elevated to Minor Basilica status, featuring Gothic architecture and the 1888 Old Shrine.',
  },
  {
    name: 'Cherok Tokun Nature Park',
    category: 'Nature',
    formattedAddress: 'Jalan Kolam, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 90,
    budgetLevel: 'Free',
    location: { latitude: 5.3582, longitude: 100.4908 },
    phone: '+604-530 1800',
    openingHours: 'Mon-Sun 07:00-19:00',
    score: 4.6,
    culturalTask: {
      title: 'Cherok Tokun Forest Trail Snap',
      description: 'Hike the scenic jungle trail and snap a photo near the hill streams or giant Tokun tree.',
      rewardPoints: 90,
    },
    description: 'Lush forest reserve with tranquil walking trails, fresh mountain streams, and the famous BM Hill trail.',
  },
  {
    name: 'Cheok Toi Mee Jawa BM',
    category: 'Food',
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.3643, longitude: 100.4605 },
    phone: '+6016-412 8899',
    openingHours: 'Mon-Sun 08:00-13:30',
    score: 4.7,
    description: 'Heritage BM Mee Jawa served with thick fragrant sweet potato gravy, crispy prawn crackers, and crushed peanuts.',
  },
  {
    name: 'Restoran Mei Le Hwa BM Dim Sum',
    category: 'Food',
    formattedAddress: 'Jalan Kulim, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 50,
    budgetLevel: 'Low',
    location: { latitude: 5.3551, longitude: 100.4725 },
    phone: '+604-538 9898',
    openingHours: 'Tue-Sun 06:00-13:00',
    score: 4.6,
    description: 'Traditional morning dim sum eatery known for handmade siew mai, har gow, steamed pork ribs, and egg tarts.',
  },
  {
    name: 'BM Famous Lao Hao You Curry Mee',
    category: 'Food',
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.3638, longitude: 100.4618 },
    phone: '+6017-488 3321',
    openingHours: 'Mon-Sun 07:30-13:00',
    score: 4.8,
    description: 'Vintage white curry mee served with homemade fragrant chili paste, coagulated blood cubes, tofu puffs, and fresh mint.',
  },
  {
    name: 'Taman Sri Rambai Hawker Centre',
    category: 'Food',
    formattedAddress: 'Taman Sri Rambai, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 55,
    budgetLevel: 'Low',
    location: { latitude: 5.3411, longitude: 100.4589 },
    phone: '+604-538 1234',
    openingHours: 'Mon-Sun 16:30-23:30',
    score: 4.6,
    description: 'Popular evening food hub in Sri Rambai offering satay, Hokkien mee, herbal duck noodle soup, and Western food.',
  },
  {
    name: 'BM Famous Hakka Mee & Yong Tau Foo',
    category: 'Food',
    formattedAddress: 'Jalan Danby, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 40,
    budgetLevel: 'Low',
    location: { latitude: 5.3646, longitude: 100.4614 },
    phone: '+6012-512 6677',
    openingHours: 'Mon-Sun 07:30-13:00',
    score: 4.7,
    description: 'Springy egg noodles tossed in savory minced pork lard sauce served with freshly stuffed fish paste bittergourd and tofu.',
  },
  {
    name: 'BM Best Cendol & Shaved Ice',
    category: 'Food',
    formattedAddress: 'Jalan Kulim, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 30,
    budgetLevel: 'Low',
    location: { latitude: 5.3562, longitude: 100.4709 },
    phone: '+6019-455 1290',
    openingHours: 'Mon-Sun 11:00-18:00',
    score: 4.7,
    description: 'Traditional BM shaved ice stall famous for rich santan cendol, ais kacang, and fresh grass jelly.',
  },
  {
    name: 'Restoran Nasi Kandar Yasmeen BM',
    category: 'Food',
    formattedAddress: 'Jalan Aston, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.3655, longitude: 100.4632 },
    phone: '+604-537 9900',
    openingHours: 'Mon-Sun 24 Hours',
    score: 4.7,
    description: 'Iconic 24-hour BM Nasi Kandar spot renowned for crispy fried chicken, black squid curry, and thick kuah campur banjir.',
  },
  {
    name: 'BM Traditional Ban Chang Kuih',
    category: 'Food',
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 25,
    budgetLevel: 'Low',
    location: { latitude: 5.3641, longitude: 100.4609 },
    phone: '+6016-554 2311',
    openingHours: 'Mon-Sun 07:00-12:30',
    score: 4.8,
    description: 'Crispy and fluffy traditional turnover pancake generously filled with crushed peanuts, sweet corn, and sugar.',
  },
  {
    name: 'De Antique Cafe BM',
    category: 'Food',
    formattedAddress: 'Lorong Ciku 2, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 60,
    budgetLevel: 'Medium',
    location: { latitude: 5.3629, longitude: 100.4628 },
    phone: '+6017-502 9918',
    openingHours: 'Thu-Tue 11:00-19:00',
    score: 4.7,
    description: 'Charming vintage cafe hidden in a BM heritage shophouse serving specialty siphon coffee, matcha, and homemade pastries.',
  },
  {
    name: 'Restoran Tokun Jaya Kopitiam',
    category: 'Food',
    formattedAddress: 'Jalan Kolam, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 45,
    budgetLevel: 'Low',
    location: { latitude: 5.3571, longitude: 100.4855 },
    phone: '+604-539 0192',
    openingHours: 'Mon-Sun 06:30-14:00',
    score: 4.6,
    description: 'Popular post-hike kopitiam by Cherok Tokun serving traditional Hainanese toast, half-boiled eggs, and aromatic Kopi O.',
  },
  {
    name: 'Mengkuang Dam Lakeside Park',
    category: 'Nature',
    formattedAddress: 'Mengkuang Dam, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 75,
    budgetLevel: 'Free',
    location: { latitude: 5.4005, longitude: 100.4938 },
    phone: '+604-500 1200',
    openingHours: 'Mon-Sun 07:00-19:00',
    score: 4.8,
    description: 'Largest dam in Penang featuring expansive lake scenery, scenic jogging trails, and a peaceful green recreation sanctuary.',
  },
  {
    name: 'Pekan Bukit Mertajam Old Market Street',
    category: 'Culture',
    formattedAddress: 'Jalan Pasar, 14000 Bukit Mertajam, Penang, Malaysia',
    area: 'Bukit Mertajam',
    durationMinutes: 60,
    budgetLevel: 'Free',
    location: { latitude: 5.3638, longitude: 100.4612 },
    phone: '+604-530 0000',
    openingHours: 'Mon-Sun 06:00-18:00',
    score: 4.7,
    description: 'Heart of BM town featuring traditional old-style dry and wet markets, Chinese medicine halls, tea merchants, and street hawkers.',
  },

  // BUTTERWORTH
  {
    name: 'Penang Bird Park',
    category: 'Nature',
    formattedAddress: 'Jalan Todak, Seberang Jaya, 13700 Butterworth, Penang, Malaysia',
    area: 'Butterworth',
    durationMinutes: 90,
    budgetLevel: 'Medium',
    location: { latitude: 5.3958, longitude: 100.3981 },
    phone: '+604-399 1899',
    openingHours: 'Mon-Sun 09:00-18:00',
    score: 4.6,
    description: 'First and largest bird park of its kind in Malaysia, housing over 300 bird species with walk-in aviaries and lush landscaped gardens.',
  },
  {
    name: 'Butterworth Art Walk',
    category: 'Art',
    formattedAddress: '1 Lorong Bagan Luar 1, 12000 Butterworth, Penang, Malaysia',
    area: 'Butterworth',
    durationMinutes: 45,
    budgetLevel: 'Free',
    location: { latitude: 5.4121, longitude: 100.3664 },
    phone: '+604-332 5000',
    openingHours: 'Mon-Sun 24 Hours',
    score: 4.6,
    description: 'Vibrant outdoor alleyway art exhibition showcasing interactive 3D murals depicting Butterworth\'s agricultural, port, and cultural history.',
  },

  // KUALA LUMPUR & SELANGOR
  {
    name: 'Central Market (Pasar Seni)',
    category: 'Heritage',
    formattedAddress: 'Jalan Hang Kasturi, City Centre, 50050 Kuala Lumpur, Malaysia',
    area: 'Kuala Lumpur',
    durationMinutes: 75,
    budgetLevel: 'Free',
    location: { latitude: 3.1453, longitude: 101.6953 },
    phone: '+603-2031 0399',
    openingHours: 'Mon-Sun 10:00-22:00',
    score: 4.8,
    description: 'Iconic 1888 Art Deco cultural landmark hosting Malaysian handicrafts, batik studios, Wau kite artisans, and traditional performances.',
  },
  {
    name: 'Batu Caves Lord Murugan Shrine',
    category: 'Heritage',
    formattedAddress: 'Gombak, 68100 Batu Caves, Selangor, Malaysia',
    area: 'Selangor',
    durationMinutes: 90,
    budgetLevel: 'Free',
    location: { latitude: 3.2379, longitude: 101.6840 },
    phone: '+603-6189 6284',
    openingHours: 'Mon-Sun 06:00-21:00',
    score: 4.8,
    culturalTask: {
      title: 'Cathedral Cave Step Ascent',
      description: 'Climb the 272 rainbow steps and photograph the limestone cathedral cave interior.',
      rewardPoints: 130,
    },
    description: 'Limestone hill comprising three major caves, world-renowned 140-ft golden Lord Murugan statue, and 272 colourful rainbow steps.',
  },

  // KELANTAN & TERENGGANU
  {
    name: 'Pasar Besar Siti Khadijah',
    category: 'Heritage',
    formattedAddress: 'Jalan Buluh Kubu, Bandar Kota Bharu, 15000 Kota Bharu, Kelantan, Malaysia',
    area: 'Kota Bharu',
    durationMinutes: 75,
    budgetLevel: 'Low',
    location: { latitude: 6.1287, longitude: 102.2392 },
    phone: '+609-748 2140',
    openingHours: 'Mon-Sun 07:00-18:00',
    score: 4.8,
    culturalTask: {
      title: 'Octagonal Market Geometry & Kuih Akok',
      description: 'Photograph the colourful central octagonal produce hall and sample warm Kuih Akok.',
      rewardPoints: 130,
    },
    description: 'Iconic 4-storey octagonal central market in Kota Bharu operated mostly by female traders, vibrant with local spices and traditional songket.',
  },
  {
    name: 'Masjid Kristal',
    category: 'Heritage',
    formattedAddress: 'Pulau Wan Man, 21000 Kuala Terengganu, Terengganu, Malaysia',
    area: 'Kuala Terengganu',
    durationMinutes: 60,
    budgetLevel: 'Free',
    location: { latitude: 5.3224, longitude: 103.1189 },
    phone: '+609-627 8888',
    openingHours: 'Mon-Sun 06:00-22:00',
    score: 4.8,
    culturalTask: {
      title: 'Crystal Reflection Snapshot',
      description: 'Photograph the gleaming crystal and glass domes reflecting over the Terengganu River.',
      rewardPoints: 120,
    },
    description: 'Magnificent grand mosque built from steel, glass, and crystal on Pulau Wan Man overlooking the scenic Terengganu River.',
  },
  {
    name: 'Borneo Cultures Museum',
    category: 'Culture',
    formattedAddress: 'Jalan Tun Abang Haji Openg, 93000 Kuching, Sarawak, Malaysia',
    area: 'Kuching',
    durationMinutes: 120,
    budgetLevel: 'Medium',
    location: { latitude: 1.5546, longitude: 110.3421 },
    phone: '+6082-536 788',
    openingHours: 'Mon-Fri 09:00-16:45, Sat-Sun 09:30-16:30',
    score: 4.9,
    culturalTask: {
      title: 'Indigenous Tribal Arts Study',
      description: 'Explore Level 3 or 4 and photograph one traditional Dayak craft or textile heirloom.',
      rewardPoints: 150,
    },
    description: 'Iconic 5-storey museum and the second largest in Southeast Asia, housing over 1,000 Borneo cultural artefacts.',
  },
];

const sampleReviewers = [
  'Tan Mei Ling',
  'Hafiz Ridzuan',
  'Sarah Jenkins',
  'Bernard Lim',
  'Chloe Dupont',
  'Kavitha Nair',
  'Chen Wei Ming',
  'Ahmad Faiz',
];

async function seed() {
  console.log(`Starting Firestore sync for ${places.length} curated venues...`);

  let vendorCount = 0;
  let placeCount = 0;
  let reviewCount = 0;

  for (const place of places) {
    const name = place.name.trim();
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
    const vendorId = `vendor_${slug}`;
    const placeId = `place_${slug}`;
    const emailSlug = slug.replace(/_/g, '');
    const vendorEmail = `${emailSlug}@myheritage.my`;

    // 1. Set Vendor
    await db.collection('vendors').doc(vendorId).set({
      uid: vendorId,
      vendorId: vendorId,
      businessName: name,
      displayName: name,
      ownerName: `${name} Management`,
      email: vendorEmail,
      phone: place.phone || '+604-500 0000',
      category: place.category || 'Heritage',
      area: place.area || 'Malaysia',
      formattedAddress: place.formattedAddress || place.area,
      location: place.location || { latitude: 5.4, longitude: 100.3 },
      role: 'vendor',
      status: 'active',
      vendorStatus: 'verified',
      score: place.score || 4.8,
      website: place.website || '',
      openingHours: place.openingHours || 'Mon-Sun 09:00-18:00',
      description: place.description || '',
      updatedAt: FieldValue.serverTimestamp(),
      createdAt: FieldValue.serverTimestamp(),
    }, { merge: true });
    vendorCount++;

    // 2. Set Place
    await db.collection('places').doc(placeId).set({
      placeId: placeId,
      vendorId: vendorId,
      name: name,
      category: place.category || 'Heritage',
      area: place.area || 'Malaysia',
      formattedAddress: place.formattedAddress || place.area,
      location: place.location || { latitude: 5.4, longitude: 100.3 },
      score: place.score || 4.8,
      durationMinutes: place.durationMinutes || 60,
      budgetLevel: place.budgetLevel || 'Low',
      phone: place.phone || '+604-500 0000',
      website: place.website || '',
      openingHours: place.openingHours || 'Mon-Sun 09:00-18:00',
      description: place.description || '',
      culturalTask: place.culturalTask || null,
      status: 'active',
      trustLabel: 'High Trust',
      updatedAt: FieldValue.serverTimestamp(),
      createdAt: FieldValue.serverTimestamp(),
    }, { merge: true });
    placeCount++;

    // 3. Seed 3-4 Valid Reviews
    const validReviews = [
      {
        rating: 5,
        comment: `Outstanding experience visiting ${name}! The authentic atmosphere, friendly hospitality, and deep cultural heritage make it a top must-visit spot in ${place.area}.`,
      },
      {
        rating: 5,
        comment: `Highly recommended! Excellent quality, vibrant local atmosphere, and thoroughly enjoyable visit. Don't forget to take photos.`,
      },
      {
        rating: 4,
        comment: `Great stop during our tour of ${place.area}. Clean surroundings, authentic offerings, and very informative.`,
      },
    ];

    for (let i = 0; i < validReviews.length; i++) {
      const reviewDocId = `rev_${slug}_valid_${i + 1}`;
      const reviewer = sampleReviewers[(vendorCount + i) % sampleReviewers.length];
      await db.collection('reviews').doc(reviewDocId).set({
        reviewId: reviewDocId,
        placeId: placeId,
        vendorId: vendorId,
        placeName: name,
        travelerName: reviewer,
        rating: validReviews[i].rating,
        comment: validReviews[i].comment,
        status: 'valid',
        mlDecision: 'valid',
        mlSuspiciousProbability: 0.04,
        mlRatingMismatch: false,
        flagReasons: [],
        createdAt: Timestamp.fromDate(new Date(Date.now() - (i + 1) * 86400000 * 3)),
      }, { merge: true });
      reviewCount++;
    }

    // 4. Seed select flagged reviews for testing ML Moderation
    if (vendorCount % 3 === 0) {
      const flaggedDocId = `rev_${slug}_flagged_1`;
      await db.collection('reviews').doc(flaggedDocId).set({
        reviewId: flaggedDocId,
        placeId: placeId,
        vendorId: vendorId,
        placeName: name,
        travelerName: 'SpamBot_Promo',
        rating: 5,
        comment: `Check out cheap discounts and free promo vouchers at http://super-discount-tourist-deals.xyz/claim now! Best place in ${place.area}!`,
        status: 'flagged',
        mlDecision: 'flagged',
        mlSuspiciousProbability: 0.96,
        mlRatingMismatch: false,
        flagReasons: ['Promotional spam URL link detected'],
        flagReason: 'Promotional spam URL link detected',
        createdAt: Timestamp.fromDate(new Date(Date.now() - 86400000)),
      }, { merge: true });
      reviewCount++;
    }
  }

  console.log(`Successfully synced directly to Firebase:`);
  console.log(`- ${vendorCount} Vendors in collection('vendors')`);
  console.log(`- ${placeCount} Places in collection('places')`);
  console.log(`- ${reviewCount} Reviews in collection('reviews')`);
}

seed().then(() => {
  process.exit(0);
}).catch(err => {
  console.error('Seeding error:', err);
  process.exit(1);
});
