import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:geolocator/geolocator.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:http/http.dart' as http;
import 'package:mobile_scanner/mobile_scanner.dart' hide GeoPoint;
import 'package:qr_flutter/qr_flutter.dart';
import 'package:share_plus/share_plus.dart';
import '../auth/auth_pages.dart';
import '../core/app_theme.dart';
import '../core/helpers.dart';
import '../core/explorer_ui.dart';
import '../core/geoapify_config.dart';
import '../core/services.dart';



part 'home/traveler_home_page.dart';
part 'daily_planner/daily_planner_page.dart';
part 'daily_planner/review_ml_model.dart';
part 'daily_planner/place_detail_page.dart';
part 'daily_planner/my_itineraries_page.dart';
part 'daily_planner/itinerary_detail_page.dart';
part 'daily_planner/itinerary_share_helper.dart';
part 'daily_planner/itinerary_image_resolver.dart';
part 'daily_planner/itinerary_edit_page.dart';
part 'cultural/cultural_tasks_page.dart';
part 'safety/safety_page.dart';
part 'safety/my_hazard_reports_page.dart';
part 'safety/create_hazard_page.dart';
part 'companion/companion_page.dart';
part 'companion/companion_membership_api.dart';
part 'companion/create_group_page.dart';
part 'companion/join_group_page.dart';
part 'companion/group_details_page.dart';
part 'companion/manage_members_page.dart';
part 'companion/group_chat_page.dart';
part 'companion/group_map_page.dart';
part 'companion/companion_location_page.dart';
part 'companion/sos_panic_page.dart';
part 'companion/sos_alerts_review_page.dart';
part 'companion/route_guidance_page.dart';
part 'rewards/rewards_page.dart';
part 'rewards/nearby_rewards_page.dart';
part 'rewards/voucher_wallet_page.dart';
part 'weather/weather_reminder_page.dart';
part 'chatbot/chatbot_page.dart';
part 'notifications/notifications_page.dart';
part 'profile/traveler_profile_page.dart';
part 'companion/private_chats_page.dart';
part 'companion/private_chat_page.dart';
